import { IIgutbetTournament } from '../redux/features/igubetTypes';

export const igubetSoccerTopLeagues: IIgutbetTournament[] = [
  {
    // england - premier league
    id: 14,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/england/premier-league.png',
    urn_id: 'sr:tournament:17',
    name: 'Premier League',
    priority: 220,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 3,
      urn_id: 'sr:category:1',
      name: 'England',
      country_code: 'ENG',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 130,
      slug: 'england',
      provider: 'betradar',
    },
    slug: 'premier-league',
    provider: 'betradar',
  },

  {
    // romania - liga 1
    id: 3967,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/romania/liga-1.png',
    urn_id: 'sr:tournament:152',
    name: 'Liga I',
    priority: 99999,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 362,
      urn_id: 'sr:category:77',
      name: 'Romania',
      country_code: 'ROU',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 99999,
      slug: 'romania',
      provider: 'betradar',
    },
    slug: 'liga-i',
    provider: 'betradar',
  },

  {
    // SPAIN - La liga
    id: 17,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/spain/primera-division.png',
    urn_id: 'sr:tournament:8',
    name: 'LaLiga',
    priority: 240,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 6,
      urn_id: 'sr:category:32',
      name: 'Spain',
      country_code: 'ESP',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 140,
      slug: 'spain',
      provider: 'betradar',
    },
    slug: 'laliga',
    provider: 'betradar',
  },

  {
    // GERMANY - Bundesliga
    id: 15,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/germany/bundesliga.png',
    urn_id: 'sr:tournament:35',
    name: 'Bundesliga',
    priority: 280,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 4,
      urn_id: 'sr:category:30',
      name: 'Germany',
      country_code: 'DEU',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 160,
      slug: 'germany',
      provider: 'betradar',
    },
    slug: 'bundesliga',
    provider: 'betradar',
  },
  {
    //  France - Ligue one
    id: 18,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/france/ligue-1.png',
    urn_id: 'sr:tournament:34',
    name: 'Ligue 1',
    priority: 300,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 7,
      urn_id: 'sr:category:7',
      name: 'France',
      country_code: 'FRA',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 170,
      slug: 'france',
      provider: 'betradar',
    },
    slug: 'ligue-1',
    provider: 'betradar',
  },

  {
    // UEFA - champions league
    id: 3,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/europe/champions-league.png',
    urn_id: 'sr:tournament:7',
    name: 'UEFA Champions League',
    priority: 170,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 2,
      urn_id: 'sr:category:393',
      name: 'International Clubs',
      country_code: '',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 120,
      slug: 'international-clubs',
      provider: 'betradar',
    },
    slug: 'uefa-champions-league',
    provider: 'betradar',
  },
  {
    // europa league
    id: 35,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/europe/europa-league.png',
    urn_id: 'sr:tournament:679',
    name: 'UEFA Europa League',
    priority: 180,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 2,
      urn_id: 'sr:category:393',
      name: 'International Clubs',
      country_code: '',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 120,
      slug: 'international-clubs',
      provider: 'betradar',
    },
    slug: 'uefa-europa-league',
    provider: 'betradar',
  },

  {
    // portugal - liga portugal
    id: 51,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/portugal/primeira-liga.png',
    urn_id: 'sr:tournament:238',
    name: 'Liga Portugal',
    priority: 99999,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 9,
      urn_id: 'sr:category:44',
      name: 'Portugal',
      country_code: 'PRT',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 99999,
      slug: 'portugal',
      provider: 'betradar',
    },
    slug: 'liga-portugal',
    provider: 'betradar',
  },
  {
    // netherlands - eredivisie
    id: 50,
    image: 'https://cdn.oddspedia.com/images/leagues/small/football/netherlands/eredivisie.png',
    urn_id: 'sr:tournament:37',
    name: 'Eredivisie',
    priority: 100,
    sport: {
      id: 1,
      urn_id: 'sr:sport:1',
      name: 'Soccer',
      key: 'soccer',
      type: 'regular',
      priority: 100,
      main_market_id: 4761,
      main_market_outcomes_count: 3,
      secondary_market_id: 219,
      secondary_market_outcomes_count: 2,
      provider: 'betradar',
    },
    category: {
      id: 8,
      urn_id: 'sr:category:35',
      name: 'Netherlands',
      country_code: 'NLD',
      sport_id: 1,
      sport_urn_id: 'sr:sport:1',
      sport_key: 'soccer',
      sport_name: 'Soccer',
      sport_type: 'regular',
      priority: 100,
      slug: 'netherlands',
      provider: 'betradar',
    },
    slug: 'eredivisie',
    provider: 'betradar',
  },
];
