import { IIgubetSport } from '../redux/features/igubetTypes';

export const iguSportIds = [1,2,16,3,4];

export const igubetSports: IIgubetSport[] = [
  {
    id: 1,
    urn_id: 'sr:sport:1',
    name: 'Soccer',
    key: 'soccer',
    type: 'regular',
    priority: 100,
    main_market_id: 4761,
    main_market_outcomes_count: 3,
    secondary_market_id: 219,
    secondary_market_outcomes_count: 2,
    provider: 'betradar',
  },
  {
    id: 2,
    urn_id: 'sr:sport:5',
    name: 'Tennis',
    key: 'tennis',
    type: 'regular',
    priority: 140,
    main_market_id: 456,
    main_market_outcomes_count: 2,
    secondary_market_id: 4204,
    secondary_market_outcomes_count: 2,
    provider: 'betradar',
  },
  {
    id: 16,
    urn_id: 'sr:sport:6',
    name: 'Handball',
    key: 'handball',
    type: 'regular',
    priority: 110,
    main_market_id: 4761,
    main_market_outcomes_count: 3,
    secondary_market_id: 219,
    secondary_market_outcomes_count: 2,
    provider: 'betradar',
  },
  {
    id: 3,
    urn_id: 'sr:sport:2',
    name: 'Basketball',
    key: 'basketball',
    type: 'regular',
    priority: 130,
    main_market_id: 278,
    main_market_outcomes_count: 2,
    secondary_market_id: 232,
    secondary_market_outcomes_count: 2,
    provider: 'betradar',
  },

  {
    id: 4,
    urn_id: 'sr:sport:4',
    name: 'Ice Hockey',
    key: 'ice-hockey',
    type: 'regular',
    priority: 4000,
    main_market_id: 4761,
    main_market_outcomes_count: 3,
    secondary_market_id: 219,
    secondary_market_outcomes_count: 2,
    provider: 'betradar',
  },
];
