import { IIgubetCategory } from '../redux/features/igubetTypes';

export const igubetCategories: IIgubetCategory[] = [
  {
    id: 8,
    urn_id: 'sr:category:35',
    name: 'Netherlands',
    country_code: 'NLD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 100,
    slug: 'netherlands',
    provider: 'betradar',
  },
  {
    id: 1,
    urn_id: 'sr:category:4',
    name: 'International',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 110,
    slug: 'international',
    provider: 'betradar',
  },
  {
    id: 2,
    urn_id: 'sr:category:393',
    name: 'International Clubs',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 120,
    slug: 'international-clubs',
    provider: 'betradar',
  },
  {
    id: 3,
    urn_id: 'sr:category:1',
    name: 'England',
    country_code: 'ENG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 130,
    slug: 'england',
    provider: 'betradar',
  },
  {
    id: 6,
    urn_id: 'sr:category:32',
    name: 'Spain',
    country_code: 'ESP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 140,
    slug: 'spain',
    provider: 'betradar',
  },
  {
    id: 5,
    urn_id: 'sr:category:31',
    name: 'Italy',
    country_code: 'ITA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 150,
    slug: 'italy',
    provider: 'betradar',
  },
  {
    id: 4,
    urn_id: 'sr:category:30',
    name: 'Germany',
    country_code: 'DEU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 160,
    slug: 'germany',
    provider: 'betradar',
  },
  {
    id: 7,
    urn_id: 'sr:category:7',
    name: 'France',
    country_code: 'FRA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 170,
    slug: 'france',
    provider: 'betradar',
  },
  {
    id: 573,
    urn_id: 'sr:category:392',
    name: 'International Youth',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 8000,
    slug: 'international-youth',
    provider: 'betradar',
  },
  {
    id: 292,
    urn_id: 'sr:category:1033',
    name: 'Electronic Leagues',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 10000,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 224,
    urn_id: 'sr:category:794',
    name: 'Guyana',
    country_code: 'GUY',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 204,
    urn_id: 'sr:category:911',
    name: 'Bermuda',
    country_code: 'BMU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 225,
    urn_id: 'sr:category:795',
    name: 'Haiti',
    country_code: 'HTI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 184,
    urn_id: 'sr:category:792',
    name: 'Barbados',
    country_code: 'BRB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 217,
    urn_id: 'sr:category:915',
    name: 'Swaziland',
    country_code: 'SWZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 205,
    urn_id: 'sr:category:912',
    name: 'Mauritius',
    country_code: 'MUS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 315,
    urn_id: 'sr:category:1111',
    name: 'Virtual Football',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 322,
    urn_id: 'sr:category:570',
    name: 'Puerto Rico',
    country_code: 'PRI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 289,
    urn_id: 'sr:category:909',
    name: 'Bahamas',
    country_code: 'BHS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 313,
    urn_id: 'sr:category:1057',
    name: 'Crimea',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 417,
    urn_id: 'sr:category:954',
    name: 'South Sudan',
    country_code: 'SSD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 377,
    urn_id: 'sr:category:869',
    name: 'Afghanistan',
    country_code: 'AFG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 519,
    urn_id: 'sr:category:1674',
    name: 'Saint Kitts and Nevis',
    country_code: 'KNA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 521,
    urn_id: 'sr:category:1748',
    name: 'Timor Leste',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 494,
    urn_id: 'sr:category:1539',
    name: 'Guadeloupe',
    country_code: 'GLP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 491,
    urn_id: 'sr:category:1519',
    name: 'Benin',
    country_code: 'BEN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 361,
    urn_id: 'sr:category:755',
    name: 'Pakistan',
    country_code: 'PAK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 599,
    urn_id: 'sr:category:882',
    name: 'New Caledonia',
    country_code: 'NCL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 374,
    urn_id: 'sr:category:840',
    name: 'Tahiti',
    country_code: 'PYF',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 415,
    urn_id: 'sr:category:952',
    name: 'Chad',
    country_code: 'TCD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 355,
    urn_id: 'sr:category:746',
    name: 'Papua New Guinea',
    country_code: 'PNG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 398,
    urn_id: 'sr:category:943',
    name: 'Somalia',
    country_code: 'SOM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 267,
    urn_id: 'sr:category:525',
    name: 'Belize',
    country_code: 'BLZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 493,
    urn_id: 'sr:category:1533',
    name: 'Dominica',
    country_code: 'DMA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 73,
    urn_id: 'sr:category:564',
    name: 'Namibia',
    country_code: 'NAM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 253,
    urn_id: 'sr:category:970',
    name: 'Sao Tome and Principe',
    country_code: 'STP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 252,
    urn_id: 'sr:category:965',
    name: 'Comoros',
    country_code: 'COM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 600,
    urn_id: 'sr:category:883',
    name: 'Vanuatu',
    country_code: 'VUT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 251,
    urn_id: 'sr:category:964',
    name: 'Guinea-bissau',
    country_code: 'GNB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 247,
    urn_id: 'sr:category:962',
    name: 'Lesotho',
    country_code: 'LSO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 601,
    urn_id: 'sr:category:884',
    name: 'Solomon Islands',
    country_code: 'SLB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 617,
    urn_id: 'sr:category:904',
    name: 'Suriname',
    country_code: 'SUR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 520,
    urn_id: 'sr:category:1677',
    name: 'Northern Cyprus',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 245,
    urn_id: 'sr:category:960',
    name: 'Equatorial Guinea',
    country_code: 'GNQ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 246,
    urn_id: 'sr:category:961',
    name: 'Madagascar',
    country_code: 'MDG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 239,
    urn_id: 'sr:category:800',
    name: 'Virtual Leagues',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 151,
    urn_id: 'sr:category:527',
    name: 'Trinidad and Tobago',
    country_code: 'TTO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 135,
    urn_id: 'sr:category:978',
    name: 'Samoa',
    country_code: 'WSM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 133,
    urn_id: 'sr:category:958',
    name: 'Guinea',
    country_code: 'GIN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 134,
    urn_id: 'sr:category:959',
    name: 'Seychelles',
    country_code: 'SYC',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 129,
    urn_id: 'sr:category:476',
    name: 'Sudan',
    country_code: 'SDN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 104,
    urn_id: 'sr:category:1020',
    name: 'Republika Srpska',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 376,
    urn_id: 'sr:category:849',
    name: 'Laos',
    country_code: 'LAO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 203,
    urn_id: 'sr:category:910',
    name: 'Cayman Islands',
    country_code: 'CYM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 103,
    urn_id: 'sr:category:100',
    name: 'Yugoslavia_NOT_IN_USE',
    country_code: 'SRB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 643,
    urn_id: 'sr:category:440',
    name: 'Yemen',
    country_code: 'YEM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 620,
    urn_id: 'sr:category:907',
    name: 'Gabon',
    country_code: 'GAB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 578,
    urn_id: 'sr:category:582',
    name: 'DR Congo',
    country_code: 'COD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 486,
    urn_id: 'sr:category:1360',
    name: 'Brunei Darussalam',
    country_code: 'BRN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 488,
    urn_id: 'sr:category:1435',
    name: 'Grenada',
    country_code: 'GRD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 487,
    urn_id: 'sr:category:1380',
    name: 'Cuba',
    country_code: 'CUB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 378,
    urn_id: 'sr:category:908',
    name: 'Guam',
    country_code: 'GUM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 222,
    urn_id: 'sr:category:711',
    name: 'Korea DPR',
    country_code: 'PRK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 331,
    urn_id: 'sr:category:257',
    name: 'Albania',
    country_code: 'ALB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'albania',
    provider: 'betradar',
  },
  {
    id: 540,
    urn_id: 'sr:category:304',
    name: 'Algeria',
    country_code: 'DZA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'algeria',
    provider: 'betradar',
  },
  {
    id: 67,
    urn_id: 'sr:category:376',
    name: 'Andorra',
    country_code: 'AND',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'andorra',
    provider: 'betradar',
  },
  {
    id: 150,
    urn_id: 'sr:category:500',
    name: 'Angola',
    country_code: 'AGO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'angola',
    provider: 'betradar',
  },
  {
    id: 399,
    urn_id: 'sr:category:944',
    name: 'Antigua and Barbuda',
    country_code: 'ATG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'antigua-and-barbuda',
    provider: 'betradar',
  },
  {
    id: 13,
    urn_id: 'sr:category:48',
    name: 'Argentina',
    country_code: 'ARG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'argentina',
    provider: 'betradar',
  },
  {
    id: 532,
    urn_id: 'sr:category:296',
    name: 'Armenia',
    country_code: 'ARM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'armenia',
    provider: 'betradar',
  },
  {
    id: 583,
    urn_id: 'sr:category:608',
    name: 'Aruba',
    country_code: 'ABW',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'aruba',
    provider: 'betradar',
  },
  {
    id: 16,
    urn_id: 'sr:category:34',
    name: 'Australia',
    country_code: 'AUS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'australia',
    provider: 'betradar',
  },
  {
    id: 522,
    urn_id: 'sr:category:17',
    name: 'Austria',
    country_code: 'AUT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'austria',
    provider: 'betradar',
  },
  {
    id: 136,
    urn_id: 'sr:category:97',
    name: 'Austria Amateur',
    country_code: 'AUT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'austria-amateur',
    provider: 'betradar',
  },
  {
    id: 533,
    urn_id: 'sr:category:297',
    name: 'Azerbaijan',
    country_code: 'AZE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'azerbaijan',
    provider: 'betradar',
  },
  {
    id: 561,
    urn_id: 'sr:category:351',
    name: 'Bahrain',
    country_code: 'BHR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bahrain',
    provider: 'betradar',
  },
  {
    id: 127,
    urn_id: 'sr:category:469',
    name: 'Bangladesh',
    country_code: 'BGD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bangladesh',
    provider: 'betradar',
  },
  {
    id: 395,
    urn_id: 'sr:category:91',
    name: 'Belarus',
    country_code: 'BLR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'belarus',
    provider: 'betradar',
  },
  {
    id: 560,
    urn_id: 'sr:category:33',
    name: 'Belgium',
    country_code: 'BEL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'belgium',
    provider: 'betradar',
  },
  {
    id: 294,
    urn_id: 'sr:category:1043',
    name: 'Bhutan',
    country_code: 'BTN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bhutan',
    provider: 'betradar',
  },
  {
    id: 71,
    urn_id: 'sr:category:379',
    name: 'Bolivia',
    country_code: 'BOL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bolivia',
    provider: 'betradar',
  },
  {
    id: 496,
    urn_id: 'sr:category:158',
    name: 'Bosnia & Herzegovina',
    country_code: 'BIH',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bosnia-and-herzegovina',
    provider: 'betradar',
  },
  {
    id: 271,
    urn_id: 'sr:category:804',
    name: 'Botswana',
    country_code: 'BWA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'botswana',
    provider: 'betradar',
  },
  {
    id: 12,
    urn_id: 'sr:category:13',
    name: 'Brazil',
    country_code: 'BRA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'brazil',
    provider: 'betradar',
  },
  {
    id: 75,
    urn_id: 'sr:category:78',
    name: 'Bulgaria',
    country_code: 'BGR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'bulgaria',
    provider: 'betradar',
  },
  {
    id: 183,
    urn_id: 'sr:category:791',
    name: 'Burkina Faso',
    country_code: 'BFA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'burkina-faso',
    provider: 'betradar',
  },
  {
    id: 93,
    urn_id: 'sr:category:956',
    name: 'Burundi',
    country_code: 'BDI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'burundi',
    provider: 'betradar',
  },
  {
    id: 185,
    urn_id: 'sr:category:852',
    name: 'Cambodia',
    country_code: 'KHM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'cambodia',
    provider: 'betradar',
  },
  {
    id: 572,
    urn_id: 'sr:category:391',
    name: 'Cameroon',
    country_code: 'CMR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'cameroon',
    provider: 'betradar',
  },
  {
    id: 146,
    urn_id: 'sr:category:388',
    name: 'Canada',
    country_code: 'CAN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'canada',
    provider: 'betradar',
  },
  {
    id: 149,
    urn_id: 'sr:category:49',
    name: 'Chile',
    country_code: 'CHL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'chile',
    provider: 'betradar',
  },
  {
    id: 15,
    urn_id: 'sr:category:99',
    name: 'China',
    country_code: 'CHN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'china',
    provider: 'betradar',
  },
  {
    id: 223,
    urn_id: 'sr:category:793',
    name: 'Chinese Taipei',
    country_code: 'TPE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'chinese-taipei',
    provider: 'betradar',
  },
  {
    id: 337,
    urn_id: 'sr:category:274',
    name: 'Colombia',
    country_code: 'COL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'colombia',
    provider: 'betradar',
  },
  {
    id: 615,
    urn_id: 'sr:category:898',
    name: 'Congo',
    country_code: 'COG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'congo',
    provider: 'betradar',
  },
  {
    id: 530,
    urn_id: 'sr:category:289',
    name: 'Costa Rica',
    country_code: 'CRI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'costa-rica',
    provider: 'betradar',
  },
  {
    id: 490,
    urn_id: 'sr:category:14',
    name: 'Croatia',
    country_code: 'HRV',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'croatia',
    provider: 'betradar',
  },
  {
    id: 371,
    urn_id: 'sr:category:827',
    name: 'Curacao',
    country_code: 'CUW',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'curacao',
    provider: 'betradar',
  },
  {
    id: 105,
    urn_id: 'sr:category:102',
    name: 'Cyprus',
    country_code: 'CYP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'cyprus',
    provider: 'betradar',
  },
  {
    id: 523,
    urn_id: 'sr:category:18',
    name: 'Czech Republic',
    country_code: 'CZE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'czech-republic',
    provider: 'betradar',
  },
  {
    id: 616,
    urn_id: 'sr:category:8',
    name: 'Denmark',
    country_code: 'DNK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'denmark',
    provider: 'betradar',
  },
  {
    id: 240,
    urn_id: 'sr:category:95',
    name: 'Denmark Amateur',
    country_code: 'DNK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'denmark-amateur',
    provider: 'betradar',
  },
  {
    id: 619,
    urn_id: 'sr:category:906',
    name: 'Djibouti',
    country_code: 'DJI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'djibouti',
    provider: 'betradar',
  },
  {
    id: 291,
    urn_id: 'sr:category:1031',
    name: 'Dominican Republic',
    country_code: 'DOM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'dominican-republic',
    provider: 'betradar',
  },
  {
    id: 503,
    urn_id: 'sr:category:165',
    name: 'Ecuador',
    country_code: 'ECU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ecuador',
    provider: 'betradar',
  },
  {
    id: 544,
    urn_id: 'sr:category:305',
    name: 'Egypt',
    country_code: 'EGY',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'egypt',
    provider: 'betradar',
  },
  {
    id: 570,
    urn_id: 'sr:category:367',
    name: 'El Salvador',
    country_code: 'SLV',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'el-salvador',
    provider: 'betradar',
  },
  {
    id: 326,
    urn_id: 'sr:category:252',
    name: 'England Amateur',
    country_code: 'ENG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'england-amateur',
    provider: 'betradar',
  },
  {
    id: 396,
    urn_id: 'sr:category:92',
    name: 'Estonia',
    country_code: 'EST',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'estonia',
    provider: 'betradar',
  },
  {
    id: 216,
    urn_id: 'sr:category:914',
    name: 'Ethiopia',
    country_code: 'ETH',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ethiopia',
    provider: 'betradar',
  },
  {
    id: 317,
    urn_id: 'sr:category:201',
    name: 'Faroe Islands',
    country_code: 'FRO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'faroe-islands',
    provider: 'betradar',
  },
  {
    id: 363,
    urn_id: 'sr:category:807',
    name: 'Fiji',
    country_code: 'FJI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'fiji',
    provider: 'betradar',
  },
  {
    id: 106,
    urn_id: 'sr:category:19',
    name: 'Finland',
    country_code: 'FIN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'finland',
    provider: 'betradar',
  },
  {
    id: 318,
    urn_id: 'sr:category:207',
    name: 'Finland Amateur',
    country_code: 'FIN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'finland-amateur',
    provider: 'betradar',
  },
  {
    id: 94,
    urn_id: 'sr:category:957',
    name: 'Gambia',
    country_code: 'GMB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'gambia',
    provider: 'betradar',
  },
  {
    id: 336,
    urn_id: 'sr:category:270',
    name: 'Georgia',
    country_code: 'GEO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'georgia',
    provider: 'betradar',
  },
  {
    id: 462,
    urn_id: 'sr:category:122',
    name: 'Germany Amateur',
    country_code: 'DEU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'germany-amateur',
    provider: 'betradar',
  },
  {
    id: 72,
    urn_id: 'sr:category:542',
    name: 'Ghana',
    country_code: 'GHA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ghana',
    provider: 'betradar',
  },
  {
    id: 397,
    urn_id: 'sr:category:938',
    name: 'Gibraltar',
    country_code: 'GIB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'gibraltar',
    provider: 'betradar',
  },
  {
    id: 585,
    urn_id: 'sr:category:67',
    name: 'Greece',
    country_code: 'GRC',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'greece',
    provider: 'betradar',
  },
  {
    id: 107,
    urn_id: 'sr:category:365',
    name: 'Guatemala',
    country_code: 'GTM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'guatemala',
    provider: 'betradar',
  },
  {
    id: 642,
    urn_id: 'sr:category:437',
    name: 'Honduras',
    country_code: 'HND',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'honduras',
    provider: 'betradar',
  },
  {
    id: 559,
    urn_id: 'sr:category:339',
    name: 'Hong Kong, China',
    country_code: 'HKG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'hong-kong-china',
    provider: 'betradar',
  },
  {
    id: 461,
    urn_id: 'sr:category:11',
    name: 'Hungary',
    country_code: 'HUN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'hungary',
    provider: 'betradar',
  },
  {
    id: 314,
    urn_id: 'sr:category:10',
    name: 'Iceland',
    country_code: 'ISL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'iceland',
    provider: 'betradar',
  },
  {
    id: 562,
    urn_id: 'sr:category:352',
    name: 'India',
    country_code: 'IND',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'india',
    provider: 'betradar',
  },
  {
    id: 66,
    urn_id: 'sr:category:368',
    name: 'Indonesia',
    country_code: 'IDN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'indonesia',
    provider: 'betradar',
  },
  {
    id: 538,
    urn_id: 'sr:category:301',
    name: 'Iran',
    country_code: 'IRN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'iran',
    provider: 'betradar',
  },
  {
    id: 645,
    urn_id: 'sr:category:490',
    name: 'Iraq',
    country_code: 'IRQ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'iraq',
    provider: 'betradar',
  },
  {
    id: 266,
    urn_id: 'sr:category:51',
    name: 'Ireland',
    country_code: 'IRL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ireland',
    provider: 'betradar',
  },
  {
    id: 584,
    urn_id: 'sr:category:66',
    name: 'Israel',
    country_code: 'ISR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'israel',
    provider: 'betradar',
  },
  {
    id: 571,
    urn_id: 'sr:category:390',
    name: 'Ivory Coast',
    country_code: 'CIV',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ivory-coast',
    provider: 'betradar',
  },
  {
    id: 263,
    urn_id: 'sr:category:502',
    name: 'Jamaica',
    country_code: 'JAM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'jamaica',
    provider: 'betradar',
  },
  {
    id: 269,
    urn_id: 'sr:category:52',
    name: 'Japan',
    country_code: 'JPN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'japan',
    provider: 'betradar',
  },
  {
    id: 557,
    urn_id: 'sr:category:329',
    name: 'Jordan',
    country_code: 'JOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'jordan',
    provider: 'betradar',
  },
  {
    id: 65,
    urn_id: 'sr:category:278',
    name: 'Kazakhstan',
    country_code: 'KAZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'kazakhstan',
    provider: 'betradar',
  },
  {
    id: 272,
    urn_id: 'sr:category:805',
    name: 'Kenya',
    country_code: 'KEN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'kenya',
    provider: 'betradar',
  },
  {
    id: 320,
    urn_id: 'sr:category:565',
    name: 'Kosovo',
    country_code: 'KOS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'kosovo',
    provider: 'betradar',
  },
  {
    id: 558,
    urn_id: 'sr:category:331',
    name: 'Kuwait',
    country_code: 'KWT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'kuwait',
    provider: 'betradar',
  },
  {
    id: 74,
    urn_id: 'sr:category:787',
    name: 'Kyrgyzstan',
    country_code: 'KGZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'kyrgyzstan',
    provider: 'betradar',
  },
  {
    id: 502,
    urn_id: 'sr:category:163',
    name: 'Latvia',
    country_code: 'LVA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'latvia',
    provider: 'betradar',
  },
  {
    id: 641,
    urn_id: 'sr:category:428',
    name: 'Lebanon',
    country_code: 'LBN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'lebanon',
    provider: 'betradar',
  },
  {
    id: 416,
    urn_id: 'sr:category:953',
    name: 'Liberia',
    country_code: 'LBR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'liberia',
    provider: 'betradar',
  },
  {
    id: 597,
    urn_id: 'sr:category:417',
    name: 'Libya',
    country_code: 'LBY',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'libya',
    provider: 'betradar',
  },
  {
    id: 265,
    urn_id: 'sr:category:512',
    name: 'Liechtenstein',
    country_code: 'LIE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'liechtenstein',
    provider: 'betradar',
  },
  {
    id: 501,
    urn_id: 'sr:category:160',
    name: 'Lithuania',
    country_code: 'LTU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'lithuania',
    provider: 'betradar',
  },
  {
    id: 524,
    urn_id: 'sr:category:197',
    name: 'Luxembourg',
    country_code: 'LUX',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'luxembourg',
    provider: 'betradar',
  },
  {
    id: 586,
    urn_id: 'sr:category:773',
    name: 'Macao',
    country_code: 'MAC',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'macao',
    provider: 'betradar',
  },
  {
    id: 372,
    urn_id: 'sr:category:829',
    name: 'Malawi',
    country_code: 'MWI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'malawi',
    provider: 'betradar',
  },
  {
    id: 200,
    urn_id: 'sr:category:85',
    name: 'Malaysia',
    country_code: 'MYS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'malaysia',
    provider: 'betradar',
  },
  {
    id: 582,
    urn_id: 'sr:category:600',
    name: 'Maldives',
    country_code: 'MDV',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'maldives',
    provider: 'betradar',
  },
  {
    id: 373,
    urn_id: 'sr:category:832',
    name: 'Mali',
    country_code: 'MLI',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'mali',
    provider: 'betradar',
  },
  {
    id: 469,
    urn_id: 'sr:category:134',
    name: 'Malta',
    country_code: 'MLT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'malta',
    provider: 'betradar',
  },
  {
    id: 321,
    urn_id: 'sr:category:567',
    name: 'Mauritania',
    country_code: 'MRT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'mauritania',
    provider: 'betradar',
  },
  {
    id: 14,
    urn_id: 'sr:category:12',
    name: 'Mexico',
    country_code: 'MEX',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'mexico',
    provider: 'betradar',
  },
  {
    id: 527,
    urn_id: 'sr:category:279',
    name: 'Moldova',
    country_code: 'MDA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'moldova',
    provider: 'betradar',
  },
  {
    id: 293,
    urn_id: 'sr:category:1042',
    name: 'Mongolia',
    country_code: 'MNG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'mongolia',
    provider: 'betradar',
  },
  {
    id: 144,
    urn_id: 'sr:category:386',
    name: 'Montenegro',
    country_code: 'MNE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'montenegro',
    provider: 'betradar',
  },
  {
    id: 539,
    urn_id: 'sr:category:303',
    name: 'Morocco',
    country_code: 'MAR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'morocco',
    provider: 'betradar',
  },
  {
    id: 273,
    urn_id: 'sr:category:806',
    name: 'Mozambique',
    country_code: 'MOZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'mozambique',
    provider: 'betradar',
  },
  {
    id: 182,
    urn_id: 'sr:category:790',
    name: 'Myanmar',
    country_code: 'MMR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'myanmar',
    provider: 'betradar',
  },
  {
    id: 618,
    urn_id: 'sr:category:905',
    name: 'Nepal',
    country_code: 'NPL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'nepal',
    provider: 'betradar',
  },
  {
    id: 489,
    urn_id: 'sr:category:148',
    name: 'New Zealand',
    country_code: 'NZL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'new-zealand',
    provider: 'betradar',
  },
  {
    id: 147,
    urn_id: 'sr:category:389',
    name: 'Nicaragua',
    country_code: 'NIC',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'nicaragua',
    provider: 'betradar',
  },
  {
    id: 254,
    urn_id: 'sr:category:971',
    name: 'Niger',
    country_code: 'NER',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'niger',
    provider: 'betradar',
  },
  {
    id: 152,
    urn_id: 'sr:category:532',
    name: 'Nigeria',
    country_code: 'NGA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'nigeria',
    provider: 'betradar',
  },
  {
    id: 467,
    urn_id: 'sr:category:130',
    name: 'Northern Ireland',
    country_code: 'NIR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'northern-ireland',
    provider: 'betradar',
  },
  {
    id: 316,
    urn_id: 'sr:category:159',
    name: 'North Macedonia',
    country_code: 'MKD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'north-macedonia',
    provider: 'betradar',
  },
  {
    id: 579,
    urn_id: 'sr:category:5',
    name: 'Norway',
    country_code: 'NOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'norway',
    provider: 'betradar',
  },
  {
    id: 400,
    urn_id: 'sr:category:94',
    name: 'Norway Amateur',
    country_code: 'NOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'norway-amateur',
    provider: 'betradar',
  },
  {
    id: 577,
    urn_id: 'sr:category:415',
    name: 'Oman',
    country_code: 'OMN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'oman',
    provider: 'betradar',
  },
  {
    id: 181,
    urn_id: 'sr:category:540',
    name: 'Palestine',
    country_code: 'PSE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'palestine',
    provider: 'betradar',
  },
  {
    id: 268,
    urn_id: 'sr:category:526',
    name: 'Panama',
    country_code: 'PAN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'panama',
    provider: 'betradar',
  },
  {
    id: 528,
    urn_id: 'sr:category:280',
    name: 'Paraguay',
    country_code: 'PRY',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'paraguay',
    provider: 'betradar',
  },
  {
    id: 319,
    urn_id: 'sr:category:20',
    name: 'Peru',
    country_code: 'PER',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'peru',
    provider: 'betradar',
  },
  {
    id: 375,
    urn_id: 'sr:category:847',
    name: 'Philippines',
    country_code: 'PHL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'philippines',
    provider: 'betradar',
  },
  {
    id: 148,
    urn_id: 'sr:category:47',
    name: 'Poland',
    country_code: 'POL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'poland',
    provider: 'betradar',
  },
  {
    id: 9,
    urn_id: 'sr:category:44',
    name: 'Portugal',
    country_code: 'PRT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'portugal',
    provider: 'betradar',
  },
  {
    id: 566,
    urn_id: 'sr:category:353',
    name: 'Qatar',
    country_code: 'QAT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'qatar',
    provider: 'betradar',
  },
  {
    id: 531,
    urn_id: 'sr:category:291',
    name: 'Republic of Korea',
    country_code: 'KOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'republic-of-korea',
    provider: 'betradar',
  },
  {
    id: 362,
    urn_id: 'sr:category:77',
    name: 'Romania',
    country_code: 'ROU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'romania',
    provider: 'betradar',
  },
  {
    id: 17,
    urn_id: 'sr:category:21',
    name: 'Russia',
    country_code: 'RUS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'russia',
    provider: 'betradar',
  },
  {
    id: 401,
    urn_id: 'sr:category:951',
    name: 'Rwanda',
    country_code: 'RWA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'rwanda',
    provider: 'betradar',
  },
  {
    id: 145,
    urn_id: 'sr:category:387',
    name: 'San Marino',
    country_code: 'SMR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'san-marino',
    provider: 'betradar',
  },
  {
    id: 555,
    urn_id: 'sr:category:310',
    name: 'Saudi Arabia',
    country_code: 'SAU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'saudi-arabia',
    provider: 'betradar',
  },
  {
    id: 10,
    urn_id: 'sr:category:22',
    name: 'Scotland',
    country_code: 'SCO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'scotland',
    provider: 'betradar',
  },
  {
    id: 602,
    urn_id: 'sr:category:886',
    name: 'Senegal',
    country_code: 'SEN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'senegal',
    provider: 'betradar',
  },
  {
    id: 492,
    urn_id: 'sr:category:152',
    name: 'Serbia',
    country_code: 'SRB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'serbia',
    provider: 'betradar',
  },
  {
    id: 248,
    urn_id: 'sr:category:963',
    name: 'Sierra Leone',
    country_code: 'SLE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'sierra-leone',
    provider: 'betradar',
  },
  {
    id: 2175,
    urn_id: 'sr:category:2123',
    name: 'Simulated Reality League',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'simulated-reality-league',
    provider: 'betradar',
  },
  {
    id: 126,
    urn_id: 'sr:category:45',
    name: 'Singapore',
    country_code: 'SGP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'singapore',
    provider: 'betradar',
  },
  {
    id: 525,
    urn_id: 'sr:category:23',
    name: 'Slovakia',
    country_code: 'SVK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'slovakia',
    provider: 'betradar',
  },
  {
    id: 526,
    urn_id: 'sr:category:24',
    name: 'Slovenia',
    country_code: 'SVN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'slovenia',
    provider: 'betradar',
  },
  {
    id: 556,
    urn_id: 'sr:category:322',
    name: 'South Africa',
    country_code: 'ZAF',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'south-africa',
    provider: 'betradar',
  },
  {
    id: 640,
    urn_id: 'sr:category:421',
    name: 'Spain Amateur',
    country_code: 'ESP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'spain-amateur',
    provider: 'betradar',
  },
  {
    id: 102,
    urn_id: 'sr:category:1009',
    name: 'Sri Lanka',
    country_code: 'LKA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'sri-lanka',
    provider: 'betradar',
  },
  {
    id: 218,
    urn_id: 'sr:category:9',
    name: 'Sweden',
    country_code: 'SWE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'sweden',
    provider: 'betradar',
  },
  {
    id: 495,
    urn_id: 'sr:category:155',
    name: 'Sweden Amateur',
    country_code: 'SWE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'sweden-amateur',
    provider: 'betradar',
  },
  {
    id: 332,
    urn_id: 'sr:category:25',
    name: 'Switzerland',
    country_code: 'CHE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'switzerland',
    provider: 'betradar',
  },
  {
    id: 142,
    urn_id: 'sr:category:380',
    name: 'Syria',
    country_code: 'SYR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'syria',
    provider: 'betradar',
  },
  {
    id: 370,
    urn_id: 'sr:category:825',
    name: 'Tajikistan',
    country_code: 'TJK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'tajikistan',
    provider: 'betradar',
  },
  {
    id: 270,
    urn_id: 'sr:category:803',
    name: 'Tanzania',
    country_code: 'TZA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'tanzania',
    provider: 'betradar',
  },
  {
    id: 644,
    urn_id: 'sr:category:485',
    name: 'Thailand',
    country_code: 'THA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'thailand',
    provider: 'betradar',
  },
  {
    id: 201,
    urn_id: 'sr:category:866',
    name: 'Togo',
    country_code: 'TGO',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'togo',
    provider: 'betradar',
  },
  {
    id: 70,
    urn_id: 'sr:category:378',
    name: 'Tunisia',
    country_code: 'TUN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'tunisia',
    provider: 'betradar',
  },
  {
    id: 128,
    urn_id: 'sr:category:46',
    name: 'Turkiye',
    country_code: 'TUR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'turkiye',
    provider: 'betradar',
  },
  {
    id: 327,
    urn_id: 'sr:category:254',
    name: 'Turkiye Amateur',
    country_code: 'TUR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'turkiye-amateur',
    provider: 'betradar',
  },
  {
    id: 202,
    urn_id: 'sr:category:867',
    name: 'Turkmenistan',
    country_code: 'TKM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'turkmenistan',
    provider: 'betradar',
  },
  {
    id: 369,
    urn_id: 'sr:category:824',
    name: 'Uganda',
    country_code: 'UGA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'uganda',
    provider: 'betradar',
  },
  {
    id: 598,
    urn_id: 'sr:category:86',
    name: 'Ukraine',
    country_code: 'UKR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'ukraine',
    provider: 'betradar',
  },
  {
    id: 534,
    urn_id: 'sr:category:299',
    name: 'United Arab Emirates',
    country_code: 'ARE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'united-arab-emirates',
    provider: 'betradar',
  },
  {
    id: 323,
    urn_id: 'sr:category:57',
    name: 'Uruguay',
    country_code: 'URY',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'uruguay',
    provider: 'betradar',
  },
  {
    id: 11,
    urn_id: 'sr:category:26',
    name: 'USA',
    country_code: 'USA',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'usa',
    provider: 'betradar',
  },
  {
    id: 143,
    urn_id: 'sr:category:385',
    name: 'Uzbekistan',
    country_code: 'UZB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'uzbekistan',
    provider: 'betradar',
  },
  {
    id: 529,
    urn_id: 'sr:category:281',
    name: 'Venezuela',
    country_code: 'VEN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'venezuela',
    provider: 'betradar',
  },
  {
    id: 108,
    urn_id: 'sr:category:366',
    name: 'Vietnam',
    country_code: 'VNM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'vietnam',
    provider: 'betradar',
  },
  {
    id: 468,
    urn_id: 'sr:category:131',
    name: 'Wales',
    country_code: 'WAL',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'wales',
    provider: 'betradar',
  },
  {
    id: 364,
    urn_id: 'sr:category:812',
    name: 'Zambia',
    country_code: 'ZMB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'zambia',
    provider: 'betradar',
  },
  {
    id: 418,
    urn_id: 'sr:category:955',
    name: 'Zanzibar',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'zanzibar',
    provider: 'betradar',
  },
  {
    id: 365,
    urn_id: 'sr:category:815',
    name: 'Zimbabwe',
    country_code: 'ZWE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'zimbabwe',
    provider: 'betradar',
  },
];
