import { IIgubetCategory } from '../redux/features/igubetTypes';
import { IOddspediaCategory } from '../redux/features/oddspediaTypes';

export const fromIgubetDidNotMatch: IIgubetCategory[] = [
  {
    id: 1,
    urn_id: 'sr:category:4',
    name: 'International',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 110,
    slug: 'international',
    provider: 'betradar',
  },
  {
    id: 2,
    urn_id: 'sr:category:393',
    name: 'International Clubs',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 120,
    slug: 'international-clubs',
    provider: 'betradar',
  },
  {
    id: 573,
    urn_id: 'sr:category:392',
    name: 'International Youth',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 8000,
    slug: 'international-youth',
    provider: 'betradar',
  },
  {
    id: 292,
    urn_id: 'sr:category:1033',
    name: 'Electronic Leagues',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 10000,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 204,
    urn_id: 'sr:category:911',
    name: 'Bermuda',
    country_code: 'BMU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 217,
    urn_id: 'sr:category:915',
    name: 'Swaziland',
    country_code: 'SWZ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 315,
    urn_id: 'sr:category:1111',
    name: 'Virtual Football',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 289,
    urn_id: 'sr:category:909',
    name: 'Bahamas',
    country_code: 'BHS',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 313,
    urn_id: 'sr:category:1057',
    name: 'Crimea',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 417,
    urn_id: 'sr:category:954',
    name: 'South Sudan', // TODO check which sudan is which
    country_code: 'SSD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 377,
    urn_id: 'sr:category:869',
    name: 'Afghanistan',
    country_code: 'AFG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 521,
    urn_id: 'sr:category:1748',
    name: 'Timor Leste',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 374,
    urn_id: 'sr:category:840',
    name: 'Tahiti',
    country_code: 'PYF',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 415,
    urn_id: 'sr:category:952',
    name: 'Chad',
    country_code: 'TCD',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 355,
    urn_id: 'sr:category:746',
    name: 'Papua New Guinea',
    country_code: 'PNG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 398,
    urn_id: 'sr:category:943',
    name: 'Somalia',
    country_code: 'SOM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 253,
    urn_id: 'sr:category:970',
    name: 'Sao Tome and Principe',
    country_code: 'STP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 600,
    urn_id: 'sr:category:883',
    name: 'Vanuatu',
    country_code: 'VUT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 251,
    urn_id: 'sr:category:964',
    name: 'Guinea-bissau',
    country_code: 'GNB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },



  {
    id: 520,
    urn_id: 'sr:category:1677',
    name: 'Northern Cyprus',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 245,
    urn_id: 'sr:category:960',
    name: 'Equatorial Guinea',
    country_code: 'GNQ',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 239,
    urn_id: 'sr:category:800',
    name: 'Virtual Leagues',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 133,
    urn_id: 'sr:category:958',
    name: 'Guinea',
    country_code: 'GIN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },

  {
    id: 129,
    urn_id: 'sr:category:476',
    name: 'Sudan',
    country_code: 'SDN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 104,
    urn_id: 'sr:category:1020',
    name: 'Republika Srpska',
    country_code: 'other',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },


  {
    id: 103,
    urn_id: 'sr:category:100',
    name: 'Yugoslavia_NOT_IN_USE',
    country_code: 'SRB',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },



  {
    id: 378,
    urn_id: 'sr:category:908',
    name: 'Guam',
    country_code: 'GUM',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 222,
    urn_id: 'sr:category:711',
    name: 'Korea DPR',
    country_code: 'PRK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: '',
    provider: 'betradar',
  },
  {
    id: 136,
    urn_id: 'sr:category:97',
    name: 'Austria Amateur',
    country_code: 'AUT',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'austria-amateur',
    provider: 'betradar',
  },

  {
    id: 223,
    urn_id: 'sr:category:793',
    name: 'Chinese Taipei',
    country_code: 'TPE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'chinese-taipei',
    provider: 'betradar',
  },
  {
    id: 240,
    urn_id: 'sr:category:95',
    name: 'Denmark Amateur',
    country_code: 'DNK',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'denmark-amateur',
    provider: 'betradar',
  },
  {
    id: 326,
    urn_id: 'sr:category:252',
    name: 'England Amateur',
    country_code: 'ENG',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'england-amateur',
    provider: 'betradar',
  },
  {
    id: 318,
    urn_id: 'sr:category:207',
    name: 'Finland Amateur',
    country_code: 'FIN',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'finland-amateur',
    provider: 'betradar',
  },
  {
    id: 462,
    urn_id: 'sr:category:122',
    name: 'Germany Amateur',
    country_code: 'DEU',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'germany-amateur',
    provider: 'betradar',
  },

  {
    id: 400,
    urn_id: 'sr:category:94',
    name: 'Norway Amateur',
    country_code: 'NOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'norway-amateur',
    provider: 'betradar',
  },

  {
    id: 531,
    urn_id: 'sr:category:291',
    name: 'Republic of Korea',
    country_code: 'KOR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'republic-of-korea',
    provider: 'betradar',
  },
  {
    id: 2175,
    urn_id: 'sr:category:2123',
    name: 'Simulated Reality League',
    country_code: '',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'simulated-reality-league',
    provider: 'betradar',
  },
  {
    id: 640,
    urn_id: 'sr:category:421',
    name: 'Spain Amateur',
    country_code: 'ESP',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'spain-amateur',
    provider: 'betradar',
  },
  {
    id: 495,
    urn_id: 'sr:category:155',
    name: 'Sweden Amateur',
    country_code: 'SWE',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'sweden-amateur',
    provider: 'betradar',
  },

  {
    id: 327,
    urn_id: 'sr:category:254',
    name: 'Turkiye Amateur',
    country_code: 'TUR',
    sport_id: 1,
    sport_urn_id: 'sr:sport:1',
    sport_key: 'soccer',
    sport_name: 'Soccer',
    sport_type: 'regular',
    priority: 99999,
    slug: 'turkiye-amateur',
    provider: 'betradar',
  },
];

export const fromOddspediaDidNotMatch: IOddspediaCategory[] = [
  {
    id: 465,
    sport_id: 1,
    name: 'South America',
    slug: 'south-america',
    slug_en: 'south-america',
    match_count_prematch_all: 54,
    match_count_prematch: 54,
    match_count_inplay: 0,
    order: 850,
  },
  {
    id: 372,
    sport_id: 1,
    name: 'North & Central America',
    slug: 'north-central-america',
    slug_en: 'north-central-america',
    match_count_prematch_all: 34,
    match_count_prematch: 34,
    match_count_inplay: 0,
    order: 860,
  },
  {
    id: 593,
    sport_id: 1,
    name: 'Australia & Oceania',
    slug: 'australia-oceania',
    slug_en: 'australia-oceania',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 870,
  },
  {
    id: 578,
    sport_id: 1,
    name: 'Asia',
    slug: 'asia',
    slug_en: 'asia',
    match_count_prematch_all: 10,
    match_count_prematch: 10,
    match_count_inplay: 0,
    order: 880,
  },
  {
    id: 430,
    sport_id: 1,
    name: 'Africa',
    slug: 'africa',
    slug_en: 'africa',
    match_count_prematch_all: 198,
    match_count_prematch: 198,
    match_count_inplay: 0,
    order: 890,
  },
  {
    id: 574,
    sport_id: 1,
    name: 'Europe',
    slug: 'europe',
    slug_en: 'europe',
    match_count_prematch_all: 514,
    match_count_prematch: 514,
    match_count_inplay: 0,
    order: 900,
  },
  {
    id: 575,
    sport_id: 1,
    name: 'World',
    slug: 'world',
    slug_en: 'world',
    match_count_prematch_all: 58,
    match_count_prematch: 58,
    match_count_inplay: 1,
    order: 1000,
  },

  {
    id: 634,
    sport_id: 1,
    name: 'French Guiana',
    slug: 'french-guiana',
    slug_en: 'french-guiana',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },



  {
    id: 562,
    sport_id: 1,
    name: 'Guinea',
    slug: 'guinea',
    slug_en: 'guinea',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },




  {
    id: 437,
    sport_id: 1,
    name: 'South Korea',
    slug: 'south-korea',
    slug_en: 'south-korea',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 509,
    sport_id: 1,
    name: 'Sudan',
    slug: 'sudan',
    slug_en: 'sudan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },

  {
    id: 586,
    sport_id: 1,
    name: 'Taiwan',
    slug: 'taiwan',
    slug_en: 'taiwan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },


];
