import { IIgubetCategory } from '../redux/features/igubetTypes';
import { IOddspediaCategory } from '../redux/features/oddspediaTypes';

export const oddspediaCategories: IOddspediaCategory[] = [
  {
    id: 465,
    sport_id: 1,
    name: 'South America',
    slug: 'south-america',
    slug_en: 'south-america',
    match_count_prematch_all: 54,
    match_count_prematch: 54,
    match_count_inplay: 0,
    order: 850,
  },
  {
    id: 372,
    sport_id: 1,
    name: 'North & Central America',
    slug: 'north-central-america',
    slug_en: 'north-central-america',
    match_count_prematch_all: 34,
    match_count_prematch: 34,
    match_count_inplay: 0,
    order: 860,
  },
  {
    id: 593,
    sport_id: 1,
    name: 'Australia & Oceania',
    slug: 'australia-oceania',
    slug_en: 'australia-oceania',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 870,
  },
  {
    id: 578,
    sport_id: 1,
    name: 'Asia',
    slug: 'asia',
    slug_en: 'asia',
    match_count_prematch_all: 10,
    match_count_prematch: 10,
    match_count_inplay: 0,
    order: 880,
  },
  {
    id: 430,
    sport_id: 1,
    name: 'Africa',
    slug: 'africa',
    slug_en: 'africa',
    match_count_prematch_all: 198,
    match_count_prematch: 198,
    match_count_inplay: 0,
    order: 890,
  },
  {
    id: 574,
    sport_id: 1,
    name: 'Europe',
    slug: 'europe',
    slug_en: 'europe',
    match_count_prematch_all: 514,
    match_count_prematch: 514,
    match_count_inplay: 0,
    order: 900,
  },
  {
    id: 575,
    sport_id: 1,
    name: 'World',
    slug: 'world',
    slug_en: 'world',
    match_count_prematch_all: 58,
    match_count_prematch: 58,
    match_count_inplay: 1,
    order: 1000,
  },
  {
    id: 375,
    sport_id: 1,
    name: 'Albania',
    slug: 'albania',
    slug_en: 'albania',
    match_count_prematch_all: 205,
    match_count_prematch: 205,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 331,
    sportradar_id: 257,
    igubet_name: 'Albania',
    igubet_country_code: 'ALB',
  },
  {
    id: 469,
    sport_id: 1,
    name: 'Algeria',
    slug: 'algeria',
    slug_en: 'algeria',
    match_count_prematch_all: 16,
    match_count_prematch: 16,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 540,
    sportradar_id: 304,
    igubet_name: 'Algeria',
    igubet_country_code: 'DZA',
  },
  {
    id: 440,
    sport_id: 1,
    name: 'Andorra',
    slug: 'andorra',
    slug_en: 'andorra',
    match_count_prematch_all: 95,
    match_count_prematch: 95,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 67,
    sportradar_id: 376,
    igubet_name: 'Andorra',
    igubet_country_code: 'AND',
  },
  {
    id: 472,
    sport_id: 1,
    name: 'Angola',
    slug: 'angola',
    slug_en: 'angola',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 150,
    sportradar_id: 500,
    igubet_name: 'Angola',
    igubet_country_code: 'AGO',
  },
  {
    id: 588,
    sport_id: 1,
    name: 'Antigua and Barbuda',
    slug: 'antigua-and-barbuda',
    slug_en: 'antigua-and-barbuda',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 399,
    sportradar_id: 944,
    igubet_name: 'Antigua and Barbuda',
    igubet_country_code: 'ATG',
  },
  {
    id: 467,
    sport_id: 1,
    name: 'Argentina',
    slug: 'argentina',
    slug_en: 'argentina',
    match_count_prematch_all: 35,
    match_count_prematch: 35,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 13,
    sportradar_id: 48,
    igubet_name: 'Argentina',
    igubet_country_code: 'ARG',
  },
  {
    id: 379,
    sport_id: 1,
    name: 'Armenia',
    slug: 'armenia',
    slug_en: 'armenia',
    match_count_prematch_all: 172,
    match_count_prematch: 172,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 532,
    sportradar_id: 296,
    igubet_name: 'Armenia',
    igubet_country_code: 'ARM',
  },
  {
    id: 629,
    sport_id: 1,
    name: 'Aruba',
    slug: 'aruba',
    slug_en: 'aruba',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 583,
    sportradar_id: 608,
    igubet_name: 'Aruba',
    igubet_country_code: 'ABW',
  },
  {
    id: 454,
    sport_id: 1,
    name: 'Australia',
    slug: 'australia',
    slug_en: 'australia',
    match_count_prematch_all: 149,
    match_count_prematch: 149,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 16,
    sportradar_id: 34,
    igubet_name: 'Australia',
    igubet_country_code: 'AUS',
  },
  {
    id: 383,
    sport_id: 1,
    name: 'Austria',
    slug: 'austria',
    slug_en: 'austria',
    match_count_prematch_all: 499,
    match_count_prematch: 499,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 522,
    sportradar_id: 17,
    igubet_name: 'Austria',
    igubet_country_code: 'AUT',
  },
  {
    id: 463,
    sport_id: 1,
    name: 'Azerbaijan',
    slug: 'azerbaijan',
    slug_en: 'azerbaijan',
    match_count_prematch_all: 205,
    match_count_prematch: 205,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 533,
    sportradar_id: 297,
    igubet_name: 'Azerbaijan',
    igubet_country_code: 'AZE',
  },
  {
    id: 473,
    sport_id: 1,
    name: 'Bahrain',
    slug: 'bahrain',
    slug_en: 'bahrain',
    match_count_prematch_all: 87,
    match_count_prematch: 87,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 561,
    sportradar_id: 351,
    igubet_name: 'Bahrain',
    igubet_country_code: 'BHR',
  },
  {
    id: 587,
    sport_id: 1,
    name: 'Bangladesh',
    slug: 'bangladesh',
    slug_en: 'bangladesh',
    match_count_prematch_all: 22,
    match_count_prematch: 22,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 127,
    sportradar_id: 469,
    igubet_name: 'Bangladesh',
    igubet_country_code: 'BGD',
  },
  {
    id: 580,
    sport_id: 1,
    name: 'Barbados',
    slug: 'barbados',
    slug_en: 'barbados',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 184,
    sportradar_id: 792,
    igubet_name: 'Barbados',
    igubet_country_code: 'BRB',
  },
  {
    id: 396,
    sport_id: 1,
    name: 'Belarus',
    slug: 'belarus',
    slug_en: 'belarus',
    match_count_prematch_all: 8,
    match_count_prematch: 8,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 395,
    sportradar_id: 91,
    igubet_name: 'Belarus',
    igubet_country_code: 'BLR',
  },
  {
    id: 377,
    sport_id: 1,
    name: 'Belgium',
    slug: 'belgium',
    slug_en: 'belgium',
    match_count_prematch_all: 250,
    match_count_prematch: 250,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 560,
    sportradar_id: 33,
    igubet_name: 'Belgium',
    igubet_country_code: 'BEL',
  },
  {
    id: 474,
    sport_id: 1,
    name: 'Belize',
    slug: 'belize',
    slug_en: 'belize',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 267,
    sportradar_id: 525,
    igubet_name: 'Belize',
    igubet_country_code: 'BLZ',
  },
  {
    id: 590,
    sport_id: 1,
    name: 'Benin',
    slug: 'benin',
    slug_en: 'benin',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 491,
    sportradar_id: 1519,
    igubet_name: 'Benin',
    igubet_country_code: 'BEN',
  },
  {
    id: 567,
    sport_id: 1,
    name: 'Bhutan',
    slug: 'bhutan',
    slug_en: 'bhutan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 294,
    sportradar_id: 1043,
    igubet_name: 'Bhutan',
    igubet_country_code: 'BTN',
  },
  {
    id: 429,
    sport_id: 1,
    name: 'Bolivia',
    slug: 'bolivia',
    slug_en: 'bolivia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 71,
    sportradar_id: 379,
    igubet_name: 'Bolivia',
    igubet_country_code: 'BOL',
  },
  {
    id: 423,
    sport_id: 1,
    name: 'Bosnia Herzegovina',
    slug: 'bosnia-herzegovina',
    slug_en: 'bosnia-herzegovina',
    match_count_prematch_all: 26,
    match_count_prematch: 26,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 496,
    sportradar_id: 158,
    igubet_name: 'Bosnia & Herzegovina',
    igubet_country_code: 'BIH',
  },
  {
    id: 603,
    sport_id: 1,
    name: 'Botswana',
    slug: 'botswana',
    slug_en: 'botswana',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 271,
    sportradar_id: 804,
    igubet_name: 'Botswana',
    igubet_country_code: 'BWA',
  },
  {
    id: 409,
    sport_id: 1,
    name: 'Brazil',
    slug: 'brazil',
    slug_en: 'brazil',
    match_count_prematch_all: 1008,
    match_count_prematch: 1008,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 12,
    sportradar_id: 13,
    igubet_name: 'Brazil',
    igubet_country_code: 'BRA',
  },
  {
    id: 535,
    sport_id: 1,
    name: 'Brunei',
    slug: 'brunei',
    slug_en: 'brunei',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 486,
    sportradar_id: 1360,
    igubet_name: 'Brunei Darussalam',
    igubet_country_code: 'BRN',
  },
  {
    id: 363,
    sport_id: 1,
    name: 'Bulgaria',
    slug: 'bulgaria',
    slug_en: 'bulgaria',
    match_count_prematch_all: 244,
    match_count_prematch: 244,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 75,
    sportradar_id: 78,
    igubet_name: 'Bulgaria',
    igubet_country_code: 'BGR',
  },
  {
    id: 527,
    sport_id: 1,
    name: 'Burkina Faso',
    slug: 'burkina-faso',
    slug_en: 'burkina-faso',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 183,
    sportradar_id: 791,
    igubet_name: 'Burkina Faso',
    igubet_country_code: 'BFA',
  },
  {
    id: 591,
    sport_id: 1,
    name: 'Burundi',
    slug: 'burundi',
    slug_en: 'burundi',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 93,
    sportradar_id: 956,
    igubet_name: 'Burundi',
    igubet_country_code: 'BDI',
  },
  {
    id: 601,
    sport_id: 1,
    name: 'Cambodia',
    slug: 'cambodia',
    slug_en: 'cambodia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 185,
    sportradar_id: 852,
    igubet_name: 'Cambodia',
    igubet_country_code: 'KHM',
  },
  {
    id: 476,
    sport_id: 1,
    name: 'Cameroon',
    slug: 'cameroon',
    slug_en: 'cameroon',
    match_count_prematch_all: 110,
    match_count_prematch: 110,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 572,
    sportradar_id: 391,
    igubet_name: 'Cameroon',
    igubet_country_code: 'CMR',
  },
  {
    id: 385,
    sport_id: 1,
    name: 'Canada',
    slug: 'canada',
    slug_en: 'canada',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 146,
    sportradar_id: 388,
    igubet_name: 'Canada',
    igubet_country_code: 'CAN',
  },
  {
    id: 600,
    sport_id: 1,
    name: 'Cayman Islands',
    slug: 'cayman-islands',
    slug_en: 'cayman-islands',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 203,
    sportradar_id: 910,
    igubet_name: 'Cayman Islands',
    igubet_country_code: 'CYM',
  },
  {
    id: 399,
    sport_id: 1,
    name: 'Chile',
    slug: 'chile',
    slug_en: 'chile',
    match_count_prematch_all: 241,
    match_count_prematch: 241,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 149,
    sportradar_id: 49,
    igubet_name: 'Chile',
    igubet_country_code: 'CHL',
  },
  {
    id: 424,
    sport_id: 1,
    name: 'China',
    slug: 'china',
    slug_en: 'china',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 15,
    sportradar_id: 99,
    igubet_name: 'China',
    igubet_country_code: 'CHN',
  },
  {
    id: 389,
    sport_id: 1,
    name: 'Colombia',
    slug: 'colombia',
    slug_en: 'colombia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 337,
    sportradar_id: 274,
    igubet_name: 'Colombia',
    igubet_country_code: 'COL',
  },
  {
    id: 516,
    sport_id: 1,
    name: 'Comoros',
    slug: 'comoros',
    slug_en: 'comoros',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 252,
    sportradar_id: 965,
    igubet_name: 'Comoros',
    igubet_country_code: 'COM',
  },
  {
    id: 519,
    sport_id: 1,
    name: 'Congo',
    slug: 'congo',
    slug_en: 'congo',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 615,
    sportradar_id: 898,
    igubet_name: 'Congo',
    igubet_country_code: 'COG',
  },
  {
    id: 477,
    sport_id: 1,
    name: 'Costa Rica',
    slug: 'costa-rica',
    slug_en: 'costa-rica',
    match_count_prematch_all: 246,
    match_count_prematch: 246,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 530,
    sportradar_id: 289,
    igubet_name: 'Costa Rica',
    igubet_country_code: 'CRI',
  },
  {
    id: 415,
    sport_id: 1,
    name: 'Croatia',
    slug: 'croatia',
    slug_en: 'croatia',
    match_count_prematch_all: 132,
    match_count_prematch: 132,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 490,
    sportradar_id: 14,
    igubet_name: 'Croatia',
    igubet_country_code: 'HRV',
  },
  {
    id: 617,
    sport_id: 1,
    name: 'Cuba',
    slug: 'cuba',
    slug_en: 'cuba',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 487,
    sportradar_id: 1380,
    igubet_name: 'Cuba',
    igubet_country_code: 'CUB',
  },
  {
    id: 627,
    sport_id: 1,
    name: 'Curacao',
    slug: 'curacao',
    slug_en: 'curacao',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 371,
    sportradar_id: 827,
    igubet_name: 'Curacao',
    igubet_country_code: 'CUW',
  },
  {
    id: 425,
    sport_id: 1,
    name: 'Cyprus',
    slug: 'cyprus',
    slug_en: 'cyprus',
    match_count_prematch_all: 70,
    match_count_prematch: 70,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 105,
    sportradar_id: 102,
    igubet_name: 'Cyprus',
    igubet_country_code: 'CYP',
  },
  {
    id: 468,
    sport_id: 1,
    name: 'Czech Republic',
    slug: 'czech-republic',
    slug_en: 'czech-republic',
    match_count_prematch_all: 611,
    match_count_prematch: 611,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 523,
    sportradar_id: 18,
    igubet_name: 'Czech Republic',
    igubet_country_code: 'CZE',
  },
  {
    id: 378,
    sport_id: 1,
    name: 'Denmark',
    slug: 'denmark',
    slug_en: 'denmark',
    match_count_prematch_all: 143,
    match_count_prematch: 143,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 616,
    sportradar_id: 8,
    igubet_name: 'Denmark',
    igubet_country_code: 'DNK',
  },
  {
    id: 606,
    sport_id: 1,
    name: 'Djibouti',
    slug: 'djibouti',
    slug_en: 'djibouti',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 619,
    sportradar_id: 906,
    igubet_name: 'Djibouti',
    igubet_country_code: 'DJI',
  },
  {
    id: 58,
    sport_id: 1,
    name: 'Dominica',
    slug: 'dominica',
    slug_en: 'dominica',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 493,
    sportradar_id: 1533,
    igubet_name: 'Dominica',
    igubet_country_code: 'DMA',
  },
  {
    id: 559,
    sport_id: 1,
    name: 'Dominican Republic',
    slug: 'dominican-republic',
    slug_en: 'dominican-republic',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 291,
    sportradar_id: 1031,
    igubet_name: 'Dominican Republic',
    igubet_country_code: 'DOM',
  },
  {
    id: 596,
    sport_id: 1,
    name: 'DR Congo',
    slug: 'dr-congo',
    slug_en: 'dr-congo',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 578,
    sportradar_id: 582,
    igubet_name: 'DR Congo',
    igubet_country_code: 'COD',
  },
  {
    id: 433,
    sport_id: 1,
    name: 'Ecuador',
    slug: 'ecuador',
    slug_en: 'ecuador',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 503,
    sportradar_id: 165,
    igubet_name: 'Ecuador',
    igubet_country_code: 'ECU',
  },
  {
    id: 464,
    sport_id: 1,
    name: 'Egypt',
    slug: 'egypt',
    slug_en: 'egypt',
    match_count_prematch_all: 74,
    match_count_prematch: 74,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 544,
    sportradar_id: 305,
    igubet_name: 'Egypt',
    igubet_country_code: 'EGY',
  },
  {
    id: 557,
    sport_id: 1,
    name: 'El Salvador',
    slug: 'el-salvador',
    slug_en: 'el-salvador',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 570,
    sportradar_id: 367,
    igubet_name: 'El Salvador',
    igubet_country_code: 'SLV',
  },
  {
    id: 382,
    sport_id: 1,
    name: 'England',
    slug: 'england',
    slug_en: 'england',
    match_count_prematch_all: 2947,
    match_count_prematch: 2947,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 3,
    sportradar_id: 1,
    igubet_name: 'England',
    igubet_country_code: 'ENG',
  },
  {
    id: 411,
    sport_id: 1,
    name: 'Estonia',
    slug: 'estonia',
    slug_en: 'estonia',
    match_count_prematch_all: 1,
    match_count_prematch: 1,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 396,
    sportradar_id: 92,
    igubet_name: 'Estonia',
    igubet_country_code: 'EST',
  },
  {
    id: 565,
    sport_id: 1,
    name: 'Ethiopia',
    slug: 'ethiopia',
    slug_en: 'ethiopia',
    match_count_prematch_all: 2,
    match_count_prematch: 2,
    match_count_inplay: 1,
    order: 0,
    igubet_id: 216,
    sportradar_id: 914,
    igubet_name: 'Ethiopia',
    igubet_country_code: 'ETH',
  },
  {
    id: 414,
    sport_id: 1,
    name: 'Faroe Islands',
    slug: 'faroe-islands',
    slug_en: 'faroe-islands',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 317,
    sportradar_id: 201,
    igubet_name: 'Faroe Islands',
    igubet_country_code: 'FRO',
  },
  {
    id: 503,
    sport_id: 1,
    name: 'Fiji',
    slug: 'fiji',
    slug_en: 'fiji',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 363,
    sportradar_id: 807,
    igubet_name: 'Fiji',
    igubet_country_code: 'FJI',
  },
  {
    id: 403,
    sport_id: 1,
    name: 'Finland',
    slug: 'finland',
    slug_en: 'finland',
    match_count_prematch_all: 25,
    match_count_prematch: 25,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 106,
    sportradar_id: 19,
    igubet_name: 'Finland',
    igubet_country_code: 'FIN',
  },
  {
    id: 408,
    sport_id: 1,
    name: 'France',
    slug: 'france',
    slug_en: 'france',
    match_count_prematch_all: 892,
    match_count_prematch: 892,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 7,
    sportradar_id: 7,
    igubet_name: 'France',
    igubet_country_code: 'FRA',
  },
  {
    id: 634,
    sport_id: 1,
    name: 'French Guiana',
    slug: 'french-guiana',
    slug_en: 'french-guiana',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 526,
    sport_id: 1,
    name: 'Gabon',
    slug: 'gabon',
    slug_en: 'gabon',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 620,
    sportradar_id: 907,
    igubet_name: 'Gabon',
    igubet_country_code: 'GAB',
  },
  {
    id: 610,
    sport_id: 1,
    name: 'Gambia',
    slug: 'gambia',
    slug_en: 'gambia',
    match_count_prematch_all: 3,
    match_count_prematch: 3,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 94,
    sportradar_id: 957,
    igubet_name: 'Gambia',
    igubet_country_code: 'GMB',
  },
  {
    id: 419,
    sport_id: 1,
    name: 'Georgia',
    slug: 'georgia',
    slug_en: 'georgia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 336,
    sportradar_id: 270,
    igubet_name: 'Georgia',
    igubet_country_code: 'GEO',
  },
  {
    id: 446,
    sport_id: 1,
    name: 'Germany',
    slug: 'germany',
    slug_en: 'germany',
    match_count_prematch_all: 3369,
    match_count_prematch: 3369,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 4,
    sportradar_id: 30,
    igubet_name: 'Germany',
    igubet_country_code: 'DEU',
  },
  {
    id: 515,
    sport_id: 1,
    name: 'Ghana',
    slug: 'ghana',
    slug_en: 'ghana',
    match_count_prematch_all: 186,
    match_count_prematch: 186,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 72,
    sportradar_id: 542,
    igubet_name: 'Ghana',
    igubet_country_code: 'GHA',
  },
  {
    id: 583,
    sport_id: 1,
    name: 'Gibraltar',
    slug: 'gibraltar',
    slug_en: 'gibraltar',
    match_count_prematch_all: 25,
    match_count_prematch: 25,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 397,
    sportradar_id: 938,
    igubet_name: 'Gibraltar',
    igubet_country_code: 'GIB',
  },
  {
    id: 394,
    sport_id: 1,
    name: 'Greece',
    slug: 'greece',
    slug_en: 'greece',
    match_count_prematch_all: 515,
    match_count_prematch: 515,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 585,
    sportradar_id: 67,
    igubet_name: 'Greece',
    igubet_country_code: 'GRC',
  },
  {
    id: 622,
    sport_id: 1,
    name: 'Grenada',
    slug: 'grenada',
    slug_en: 'grenada',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 488,
    sportradar_id: 1435,
    igubet_name: 'Grenada',
    igubet_country_code: 'GRD',
  },
  {
    id: 594,
    sport_id: 1,
    name: 'Guadeloupe',
    slug: 'guadeloupe',
    slug_en: 'guadeloupe',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 494,
    sportradar_id: 1539,
    igubet_name: 'Guadeloupe',
    igubet_country_code: 'GLP',
  },
  {
    id: 478,
    sport_id: 1,
    name: 'Guatemala',
    slug: 'guatemala',
    slug_en: 'guatemala',
    match_count_prematch_all: 132,
    match_count_prematch: 132,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 107,
    sportradar_id: 365,
    igubet_name: 'Guatemala',
    igubet_country_code: 'GTM',
  },
  {
    id: 562,
    sport_id: 1,
    name: 'Guinea',
    slug: 'guinea',
    slug_en: 'guinea',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 595,
    sport_id: 1,
    name: 'Guyana',
    slug: 'guyana',
    slug_en: 'guyana',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 224,
    sportradar_id: 794,
    igubet_name: 'Guyana',
    igubet_country_code: 'GUY',
  },
  {
    id: 604,
    sport_id: 1,
    name: 'Haiti',
    slug: 'haiti',
    slug_en: 'haiti',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 225,
    sportradar_id: 795,
    igubet_name: 'Haiti',
    igubet_country_code: 'HTI',
  },
  {
    id: 480,
    sport_id: 1,
    name: 'Honduras',
    slug: 'honduras',
    slug_en: 'honduras',
    match_count_prematch_all: 45,
    match_count_prematch: 45,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 642,
    sportradar_id: 437,
    igubet_name: 'Honduras',
    igubet_country_code: 'HND',
  },
  {
    id: 479,
    sport_id: 1,
    name: 'Hong Kong',
    slug: 'hong-kong',
    slug_en: 'hong-kong',
    match_count_prematch_all: 146,
    match_count_prematch: 146,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 559,
    sportradar_id: 339,
    igubet_name: 'Hong Kong, China',
    igubet_country_code: 'HKG',
  },
  {
    id: 412,
    sport_id: 1,
    name: 'Hungary',
    slug: 'hungary',
    slug_en: 'hungary',
    match_count_prematch_all: 342,
    match_count_prematch: 342,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 461,
    sportradar_id: 11,
    igubet_name: 'Hungary',
    igubet_country_code: 'HUN',
  },
  {
    id: 373,
    sport_id: 1,
    name: 'Iceland',
    slug: 'iceland',
    slug_en: 'iceland',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 314,
    sportradar_id: 10,
    igubet_name: 'Iceland',
    igubet_country_code: 'ISL',
  },
  {
    id: 481,
    sport_id: 1,
    name: 'India',
    slug: 'india',
    slug_en: 'india',
    match_count_prematch_all: 100,
    match_count_prematch: 100,
    match_count_inplay: 3,
    order: 0,
    igubet_id: 562,
    sportradar_id: 352,
    igubet_name: 'India',
    igubet_country_code: 'IND',
  },
  {
    id: 522,
    sport_id: 1,
    name: 'Indonesia',
    slug: 'indonesia',
    slug_en: 'indonesia',
    match_count_prematch_all: 122,
    match_count_prematch: 122,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 66,
    sportradar_id: 368,
    igubet_name: 'Indonesia',
    igubet_country_code: 'IDN',
  },
  {
    id: 361,
    sport_id: 1,
    name: 'Iran',
    slug: 'iran',
    slug_en: 'iran',
    match_count_prematch_all: 93,
    match_count_prematch: 93,
    match_count_inplay: 1,
    order: 0,
    igubet_id: 538,
    sportradar_id: 301,
    igubet_name: 'Iran',
    igubet_country_code: 'IRN',
  },
  {
    id: 482,
    sport_id: 1,
    name: 'Iraq',
    slug: 'iraq',
    slug_en: 'iraq',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 645,
    sportradar_id: 490,
    igubet_name: 'Iraq',
    igubet_country_code: 'IRQ',
  },
  {
    id: 435,
    sport_id: 1,
    name: 'Ireland',
    slug: 'ireland',
    slug_en: 'ireland',
    match_count_prematch_all: 18,
    match_count_prematch: 18,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 266,
    sportradar_id: 51,
    igubet_name: 'Ireland',
    igubet_country_code: 'IRL',
  },
  {
    id: 365,
    sport_id: 1,
    name: 'Israel',
    slug: 'israel',
    slug_en: 'israel',
    match_count_prematch_all: 183,
    match_count_prematch: 183,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 584,
    sportradar_id: 66,
    igubet_name: 'Israel',
    igubet_country_code: 'ISR',
  },
  {
    id: 398,
    sport_id: 1,
    name: 'Italy',
    slug: 'italy',
    slug_en: 'italy',
    match_count_prematch_all: 2599,
    match_count_prematch: 2599,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 5,
    sportradar_id: 31,
    igubet_name: 'Italy',
    igubet_country_code: 'ITA',
  },
  {
    id: 475,
    sport_id: 1,
    name: 'Ivory Coast',
    slug: 'ivory-coast',
    slug_en: 'ivory-coast',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 571,
    sportradar_id: 390,
    igubet_name: 'Ivory Coast',
    igubet_country_code: 'CIV',
  },
  {
    id: 483,
    sport_id: 1,
    name: 'Jamaica',
    slug: 'jamaica',
    slug_en: 'jamaica',
    match_count_prematch_all: 121,
    match_count_prematch: 121,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 263,
    sportradar_id: 502,
    igubet_name: 'Jamaica',
    igubet_country_code: 'JAM',
  },
  {
    id: 416,
    sport_id: 1,
    name: 'Japan',
    slug: 'japan',
    slug_en: 'japan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 269,
    sportradar_id: 52,
    igubet_name: 'Japan',
    igubet_country_code: 'JPN',
  },
  {
    id: 484,
    sport_id: 1,
    name: 'Jordan',
    slug: 'jordan',
    slug_en: 'jordan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 557,
    sportradar_id: 329,
    igubet_name: 'Jordan',
    igubet_country_code: 'JOR',
  },
  {
    id: 445,
    sport_id: 1,
    name: 'Kazakhstan',
    slug: 'kazakhstan',
    slug_en: 'kazakhstan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 65,
    sportradar_id: 278,
    igubet_name: 'Kazakhstan',
    igubet_country_code: 'KAZ',
  },
  {
    id: 560,
    sport_id: 1,
    name: 'Kenya',
    slug: 'kenya',
    slug_en: 'kenya',
    match_count_prematch_all: 152,
    match_count_prematch: 152,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 272,
    sportradar_id: 805,
    igubet_name: 'Kenya',
    igubet_country_code: 'KEN',
  },
  {
    id: 555,
    sport_id: 1,
    name: 'Kosovo',
    slug: 'kosovo',
    slug_en: 'kosovo',
    match_count_prematch_all: 7,
    match_count_prematch: 7,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 320,
    sportradar_id: 565,
    igubet_name: 'Kosovo',
    igubet_country_code: 'KOS',
  },
  {
    id: 371,
    sport_id: 1,
    name: 'Kuwait',
    slug: 'kuwait',
    slug_en: 'kuwait',
    match_count_prematch_all: 35,
    match_count_prematch: 35,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 558,
    sportradar_id: 331,
    igubet_name: 'Kuwait',
    igubet_country_code: 'KWT',
  },
  {
    id: 500,
    sport_id: 1,
    name: 'Kyrgyzstan',
    slug: 'kyrgyzstan',
    slug_en: 'kyrgyzstan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 74,
    sportradar_id: 787,
    igubet_name: 'Kyrgyzstan',
    igubet_country_code: 'KGZ',
  },
  {
    id: 599,
    sport_id: 1,
    name: 'Laos',
    slug: 'laos',
    slug_en: 'laos',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 376,
    sportradar_id: 849,
    igubet_name: 'Laos',
    igubet_country_code: 'LAO',
  },
  {
    id: 370,
    sport_id: 1,
    name: 'Latvia',
    slug: 'latvia',
    slug_en: 'latvia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 502,
    sportradar_id: 163,
    igubet_name: 'Latvia',
    igubet_country_code: 'LVA',
  },
  {
    id: 485,
    sport_id: 1,
    name: 'Lebanon',
    slug: 'lebanon',
    slug_en: 'lebanon',
    match_count_prematch_all: 24,
    match_count_prematch: 24,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 641,
    sportradar_id: 428,
    igubet_name: 'Lebanon',
    igubet_country_code: 'LBN',
  },
  {
    id: 626,
    sport_id: 1,
    name: 'Lesotho',
    slug: 'lesotho',
    slug_en: 'lesotho',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 247,
    sportradar_id: 962,
    igubet_name: 'Lesotho',
    igubet_country_code: 'LSO',
  },
  {
    id: 520,
    sport_id: 1,
    name: 'Liberia',
    slug: 'liberia',
    slug_en: 'liberia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 416,
    sportradar_id: 953,
    igubet_name: 'Liberia',
    igubet_country_code: 'LBR',
  },
  {
    id: 507,
    sport_id: 1,
    name: 'Libya',
    slug: 'libya',
    slug_en: 'libya',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 597,
    sportradar_id: 417,
    igubet_name: 'Libya',
    igubet_country_code: 'LBY',
  },
  {
    id: 387,
    sport_id: 1,
    name: 'Liechtenstein',
    slug: 'liechtenstein',
    slug_en: 'liechtenstein',
    match_count_prematch_all: 1,
    match_count_prematch: 1,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 265,
    sportradar_id: 512,
    igubet_name: 'Liechtenstein',
    igubet_country_code: 'LIE',
  },
  {
    id: 401,
    sport_id: 1,
    name: 'Lithuania',
    slug: 'lithuania',
    slug_en: 'lithuania',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 501,
    sportradar_id: 160,
    igubet_name: 'Lithuania',
    igubet_country_code: 'LTU',
  },
  {
    id: 392,
    sport_id: 1,
    name: 'Luxembourg',
    slug: 'luxembourg',
    slug_en: 'luxembourg',
    match_count_prematch_all: 248,
    match_count_prematch: 248,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 524,
    sportradar_id: 197,
    igubet_name: 'Luxembourg',
    igubet_country_code: 'LUX',
  },
  {
    id: 584,
    sport_id: 1,
    name: 'Macao',
    slug: 'macao',
    slug_en: 'macao',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 586,
    sportradar_id: 773,
    igubet_name: 'Macao',
    igubet_country_code: 'MAC',
  },
  {
    id: 614,
    sport_id: 1,
    name: 'Madagascar',
    slug: 'madagascar',
    slug_en: 'madagascar',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 246,
    sportradar_id: 961,
    igubet_name: 'Madagascar',
    igubet_country_code: 'MDG',
  },
  {
    id: 602,
    sport_id: 1,
    name: 'Malawi',
    slug: 'malawi',
    slug_en: 'malawi',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 372,
    sportradar_id: 829,
    igubet_name: 'Malawi',
    igubet_country_code: 'MWI',
  },
  {
    id: 393,
    sport_id: 1,
    name: 'Malaysia',
    slug: 'malaysia',
    slug_en: 'malaysia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 200,
    sportradar_id: 85,
    igubet_name: 'Malaysia',
    igubet_country_code: 'MYS',
  },
  {
    id: 486,
    sport_id: 1,
    name: 'Maldives',
    slug: 'maldives',
    slug_en: 'maldives',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 582,
    sportradar_id: 600,
    igubet_name: 'Maldives',
    igubet_country_code: 'MDV',
  },
  {
    id: 525,
    sport_id: 1,
    name: 'Mali',
    slug: 'mali',
    slug_en: 'mali',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 373,
    sportradar_id: 832,
    igubet_name: 'Mali',
    igubet_country_code: 'MLI',
  },
  {
    id: 390,
    sport_id: 1,
    name: 'Malta',
    slug: 'malta',
    slug_en: 'malta',
    match_count_prematch_all: 35,
    match_count_prematch: 35,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 469,
    sportradar_id: 134,
    igubet_name: 'Malta',
    igubet_country_code: 'MLT',
  },
  {
    id: 517,
    sport_id: 1,
    name: 'Mauritania',
    slug: 'mauritania',
    slug_en: 'mauritania',
    match_count_prematch_all: 1,
    match_count_prematch: 1,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 321,
    sportradar_id: 567,
    igubet_name: 'Mauritania',
    igubet_country_code: 'MRT',
  },
  {
    id: 571,
    sport_id: 1,
    name: 'Mauritius',
    slug: 'mauritius',
    slug_en: 'mauritius',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 205,
    sportradar_id: 912,
    igubet_name: 'Mauritius',
    igubet_country_code: 'MUS',
  },
  {
    id: 413,
    sport_id: 1,
    name: 'Mexico',
    slug: 'mexico',
    slug_en: 'mexico',
    match_count_prematch_all: 589,
    match_count_prematch: 589,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 14,
    sportradar_id: 12,
    igubet_name: 'Mexico',
    igubet_country_code: 'MEX',
  },
  {
    id: 374,
    sport_id: 1,
    name: 'Moldova',
    slug: 'moldova',
    slug_en: 'moldova',
    match_count_prematch_all: 79,
    match_count_prematch: 79,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 527,
    sportradar_id: 279,
    igubet_name: 'Moldova',
    igubet_country_code: 'MDA',
  },
  {
    id: 612,
    sport_id: 1,
    name: 'Mongolia',
    slug: 'mongolia',
    slug_en: 'mongolia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 293,
    sportradar_id: 1042,
    igubet_name: 'Mongolia',
    igubet_country_code: 'MNG',
  },
  {
    id: 493,
    sport_id: 1,
    name: 'Montenegro',
    slug: 'montenegro',
    slug_en: 'montenegro',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 144,
    sportradar_id: 386,
    igubet_name: 'Montenegro',
    igubet_country_code: 'MNE',
  },
  {
    id: 581,
    sport_id: 1,
    name: 'Morocco',
    slug: 'morocco',
    slug_en: 'morocco',
    match_count_prematch_all: 7,
    match_count_prematch: 7,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 539,
    sportradar_id: 303,
    igubet_name: 'Morocco',
    igubet_country_code: 'MAR',
  },
  {
    id: 572,
    sport_id: 1,
    name: 'Mozambique',
    slug: 'mozambique',
    slug_en: 'mozambique',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 273,
    sportradar_id: 806,
    igubet_name: 'Mozambique',
    igubet_country_code: 'MOZ',
  },
  {
    id: 568,
    sport_id: 1,
    name: 'Myanmar',
    slug: 'myanmar',
    slug_en: 'myanmar',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 182,
    sportradar_id: 790,
    igubet_name: 'Myanmar',
    igubet_country_code: 'MMR',
  },
  {
    id: 573,
    sport_id: 1,
    name: 'Namibia',
    slug: 'namibia',
    slug_en: 'namibia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 73,
    sportradar_id: 564,
    igubet_name: 'Namibia',
    igubet_country_code: 'NAM',
  },
  {
    id: 566,
    sport_id: 1,
    name: 'Nepal',
    slug: 'nepal',
    slug_en: 'nepal',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 618,
    sportradar_id: 905,
    igubet_name: 'Nepal',
    igubet_country_code: 'NPL',
  },
  {
    id: 407,
    sport_id: 1,
    name: 'Netherlands',
    slug: 'netherlands',
    slug_en: 'netherlands',
    match_count_prematch_all: 577,
    match_count_prematch: 577,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 8,
    sportradar_id: 35,
    igubet_name: 'Netherlands',
    igubet_country_code: 'NLD',
  },
  {
    id: 589,
    sport_id: 1,
    name: 'New Caledonia',
    slug: 'new-caledonia',
    slug_en: 'new-caledonia',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 599,
    sportradar_id: 882,
    igubet_name: 'New Caledonia',
    igubet_country_code: 'NCL',
  },
  {
    id: 488,
    sport_id: 1,
    name: 'New Zealand',
    slug: 'new-zealand',
    slug_en: 'new-zealand',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 489,
    sportradar_id: 148,
    igubet_name: 'New Zealand',
    igubet_country_code: 'NZL',
  },
  {
    id: 563,
    sport_id: 1,
    name: 'Nicaragua',
    slug: 'nicaragua',
    slug_en: 'nicaragua',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 147,
    sportradar_id: 389,
    igubet_name: 'Nicaragua',
    igubet_country_code: 'NIC',
  },
  {
    id: 487,
    sport_id: 1,
    name: 'Niger',
    slug: 'niger',
    slug_en: 'niger',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 254,
    sportradar_id: 971,
    igubet_name: 'Niger',
    igubet_country_code: 'NER',
  },
  {
    id: 564,
    sport_id: 1,
    name: 'Nigeria',
    slug: 'nigeria',
    slug_en: 'nigeria',
    match_count_prematch_all: 61,
    match_count_prematch: 61,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 152,
    sportradar_id: 532,
    igubet_name: 'Nigeria',
    igubet_country_code: 'NGA',
  },
  {
    id: 426,
    sport_id: 1,
    name: 'Northern Ireland',
    slug: 'northern-ireland',
    slug_en: 'northern-ireland',
    match_count_prematch_all: 139,
    match_count_prematch: 139,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 467,
    sportradar_id: 130,
    igubet_name: 'Northern Ireland',
    igubet_country_code: 'NIR',
  },
  {
    id: 384,
    sport_id: 1,
    name: 'North Macedonia',
    slug: 'north-macedonia',
    slug_en: 'north-macedonia',
    match_count_prematch_all: 144,
    match_count_prematch: 144,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 316,
    sportradar_id: 159,
    igubet_name: 'North Macedonia',
    igubet_country_code: 'MKD',
  },
  {
    id: 431,
    sport_id: 1,
    name: 'Norway',
    slug: 'norway',
    slug_en: 'norway',
    match_count_prematch_all: 540,
    match_count_prematch: 540,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 579,
    sportradar_id: 5,
    igubet_name: 'Norway',
    igubet_country_code: 'NOR',
  },
  {
    id: 380,
    sport_id: 1,
    name: 'Oman',
    slug: 'oman',
    slug_en: 'oman',
    match_count_prematch_all: 35,
    match_count_prematch: 35,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 577,
    sportradar_id: 415,
    igubet_name: 'Oman',
    igubet_country_code: 'OMN',
  },
  {
    id: 495,
    sport_id: 1,
    name: 'Pakistan',
    slug: 'pakistan',
    slug_en: 'pakistan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 361,
    sportradar_id: 755,
    igubet_name: 'Pakistan',
    igubet_country_code: 'PAK',
  },
  {
    id: 569,
    sport_id: 1,
    name: 'Palestinian Territory',
    slug: 'palestinian-territory',
    slug_en: 'palestinian-territory',
    match_count_prematch_all: 66,
    match_count_prematch: 66,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 181,
    sportradar_id: 540,
    igubet_name: 'Palestine',
    igubet_country_code: 'PSE',
  },
  {
    id: 489,
    sport_id: 1,
    name: 'Panama',
    slug: 'panama',
    slug_en: 'panama',
    match_count_prematch_all: 5,
    match_count_prematch: 5,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 268,
    sportradar_id: 526,
    igubet_name: 'Panama',
    igubet_country_code: 'PAN',
  },
  {
    id: 448,
    sport_id: 1,
    name: 'Paraguay',
    slug: 'paraguay',
    slug_en: 'paraguay',
    match_count_prematch_all: 12,
    match_count_prematch: 12,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 528,
    sportradar_id: 280,
    igubet_name: 'Paraguay',
    igubet_country_code: 'PRY',
  },
  {
    id: 457,
    sport_id: 1,
    name: 'Peru',
    slug: 'peru',
    slug_en: 'peru',
    match_count_prematch_all: 8,
    match_count_prematch: 8,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 319,
    sportradar_id: 20,
    igubet_name: 'Peru',
    igubet_country_code: 'PER',
  },
  {
    id: 533,
    sport_id: 1,
    name: 'Philippines',
    slug: 'philippines',
    slug_en: 'philippines',
    match_count_prematch_all: 26,
    match_count_prematch: 26,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 375,
    sportradar_id: 847,
    igubet_name: 'Philippines',
    igubet_country_code: 'PHL',
  },
  {
    id: 386,
    sport_id: 1,
    name: 'Poland',
    slug: 'poland',
    slug_en: 'poland',
    match_count_prematch_all: 1171,
    match_count_prematch: 1171,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 148,
    sportradar_id: 47,
    igubet_name: 'Poland',
    igubet_country_code: 'POL',
  },
  {
    id: 418,
    sport_id: 1,
    name: 'Portugal',
    slug: 'portugal',
    slug_en: 'portugal',
    match_count_prematch_all: 907,
    match_count_prematch: 907,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 9,
    sportradar_id: 44,
    igubet_name: 'Portugal',
    igubet_country_code: 'PRT',
  },
  {
    id: 536,
    sport_id: 1,
    name: 'Puerto Rico',
    slug: 'puerto-rico',
    slug_en: 'puerto-rico',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 322,
    sportradar_id: 570,
    igubet_name: 'Puerto Rico',
    igubet_country_code: 'PRI',
  },
  {
    id: 369,
    sport_id: 1,
    name: 'Qatar',
    slug: 'qatar',
    slug_en: 'qatar',
    match_count_prematch_all: 53,
    match_count_prematch: 53,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 566,
    sportradar_id: 353,
    igubet_name: 'Qatar',
    igubet_country_code: 'QAT',
  },
  {
    id: 400,
    sport_id: 1,
    name: 'Romania',
    slug: 'romania',
    slug_en: 'romania',
    match_count_prematch_all: 106,
    match_count_prematch: 106,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 362,
    sportradar_id: 77,
    igubet_name: 'Romania',
    igubet_country_code: 'ROU',
  },
  {
    id: 368,
    sport_id: 1,
    name: 'Russia',
    slug: 'russia',
    slug_en: 'russia',
    match_count_prematch_all: 411,
    match_count_prematch: 411,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 17,
    sportradar_id: 21,
    igubet_name: 'Russia',
    igubet_country_code: 'RUS',
  },
  {
    id: 510,
    sport_id: 1,
    name: 'Rwanda',
    slug: 'rwanda',
    slug_en: 'rwanda',
    match_count_prematch_all: 70,
    match_count_prematch: 70,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 401,
    sportradar_id: 951,
    igubet_name: 'Rwanda',
    igubet_country_code: 'RWA',
  },
  {
    id: 613,
    sport_id: 1,
    name: 'Saint Kitts and Nevis',
    slug: 'saint-kitts-and-nevis',
    slug_en: 'saint-kitts-and-nevis',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 519,
    sportradar_id: 1674,
    igubet_name: 'Saint Kitts and Nevis',
    igubet_country_code: 'KNA',
  },
  {
    id: 592,
    sport_id: 1,
    name: 'Samoa',
    slug: 'samoa',
    slug_en: 'samoa',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 135,
    sportradar_id: 978,
    igubet_name: 'Samoa',
    igubet_country_code: 'WSM',
  },
  {
    id: 579,
    sport_id: 1,
    name: 'San Marino',
    slug: 'san-marino',
    slug_en: 'san-marino',
    match_count_prematch_all: 116,
    match_count_prematch: 116,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 145,
    sportradar_id: 387,
    igubet_name: 'San Marino',
    igubet_country_code: 'SMR',
  },
  {
    id: 462,
    sport_id: 1,
    name: 'Saudi Arabia',
    slug: 'saudi-arabia',
    slug_en: 'saudi-arabia',
    match_count_prematch_all: 193,
    match_count_prematch: 193,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 555,
    sportradar_id: 310,
    igubet_name: 'Saudi Arabia',
    igubet_country_code: 'SAU',
  },
  {
    id: 449,
    sport_id: 1,
    name: 'Scotland',
    slug: 'scotland',
    slug_en: 'scotland',
    match_count_prematch_all: 395,
    match_count_prematch: 395,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 10,
    sportradar_id: 22,
    igubet_name: 'Scotland',
    igubet_country_code: 'SCO',
  },
  {
    id: 518,
    sport_id: 1,
    name: 'Senegal',
    slug: 'senegal',
    slug_en: 'senegal',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 602,
    sportradar_id: 886,
    igubet_name: 'Senegal',
    igubet_country_code: 'SEN',
  },
  {
    id: 428,
    sport_id: 1,
    name: 'Serbia',
    slug: 'serbia',
    slug_en: 'serbia',
    match_count_prematch_all: 165,
    match_count_prematch: 165,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 492,
    sportradar_id: 152,
    igubet_name: 'Serbia',
    igubet_country_code: 'SRB',
  },
  {
    id: 611,
    sport_id: 1,
    name: 'Seychelles',
    slug: 'seychelles',
    slug_en: 'seychelles',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 134,
    sportradar_id: 959,
    igubet_name: 'Seychelles',
    igubet_country_code: 'SYC',
  },
  {
    id: 615,
    sport_id: 1,
    name: 'Sierra Leone',
    slug: 'sierra-leone',
    slug_en: 'sierra-leone',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 248,
    sportradar_id: 963,
    igubet_name: 'Sierra Leone',
    igubet_country_code: 'SLE',
  },
  {
    id: 404,
    sport_id: 1,
    name: 'Singapore',
    slug: 'singapore',
    slug_en: 'singapore',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 126,
    sportradar_id: 45,
    igubet_name: 'Singapore',
    igubet_country_code: 'SGP',
  },
  {
    id: 391,
    sport_id: 1,
    name: 'Slovakia',
    slug: 'slovakia',
    slug_en: 'slovakia',
    match_count_prematch_all: 232,
    match_count_prematch: 232,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 525,
    sportradar_id: 23,
    igubet_name: 'Slovakia',
    igubet_country_code: 'SVK',
  },
  {
    id: 441,
    sport_id: 1,
    name: 'Slovenia',
    slug: 'slovenia',
    slug_en: 'slovenia',
    match_count_prematch_all: 184,
    match_count_prematch: 184,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 526,
    sportradar_id: 24,
    igubet_name: 'Slovenia',
    igubet_country_code: 'SVN',
  },
  {
    id: 597,
    sport_id: 1,
    name: 'Solomon Islands',
    slug: 'solomon-islands',
    slug_en: 'solomon-islands',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 601,
    sportradar_id: 884,
    igubet_name: 'Solomon Islands',
    igubet_country_code: 'SLB',
  },
  {
    id: 447,
    sport_id: 1,
    name: 'South Africa',
    slug: 'south-africa',
    slug_en: 'south-africa',
    match_count_prematch_all: 242,
    match_count_prematch: 242,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 556,
    sportradar_id: 322,
    igubet_name: 'South Africa',
    igubet_country_code: 'ZAF',
  },
  {
    id: 437,
    sport_id: 1,
    name: 'South Korea',
    slug: 'south-korea',
    slug_en: 'south-korea',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 438,
    sport_id: 1,
    name: 'Spain',
    slug: 'spain',
    slug_en: 'spain',
    match_count_prematch_all: 2749,
    match_count_prematch: 2749,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 6,
    sportradar_id: 32,
    igubet_name: 'Spain',
    igubet_country_code: 'ESP',
  },
  {
    id: 532,
    sport_id: 1,
    name: 'Sri Lanka',
    slug: 'sri-lanka',
    slug_en: 'sri-lanka',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 102,
    sportradar_id: 1009,
    igubet_name: 'Sri Lanka',
    igubet_country_code: 'LKA',
  },
  {
    id: 509,
    sport_id: 1,
    name: 'Sudan',
    slug: 'sudan',
    slug_en: 'sudan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 570,
    sport_id: 1,
    name: 'Suriname',
    slug: 'suriname',
    slug_en: 'suriname',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 617,
    sportradar_id: 904,
    igubet_name: 'Suriname',
    igubet_country_code: 'SUR',
  },
  {
    id: 410,
    sport_id: 1,
    name: 'Sweden',
    slug: 'sweden',
    slug_en: 'sweden',
    match_count_prematch_all: 635,
    match_count_prematch: 635,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 218,
    sportradar_id: 9,
    igubet_name: 'Sweden',
    igubet_country_code: 'SWE',
  },
  {
    id: 451,
    sport_id: 1,
    name: 'Switzerland',
    slug: 'switzerland',
    slug_en: 'switzerland',
    match_count_prematch_all: 378,
    match_count_prematch: 378,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 332,
    sportradar_id: 25,
    igubet_name: 'Switzerland',
    igubet_country_code: 'CHE',
  },
  {
    id: 442,
    sport_id: 1,
    name: 'Syria',
    slug: 'syria',
    slug_en: 'syria',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 142,
    sportradar_id: 380,
    igubet_name: 'Syria',
    igubet_country_code: 'SYR',
  },
  {
    id: 586,
    sport_id: 1,
    name: 'Taiwan',
    slug: 'taiwan',
    slug_en: 'taiwan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
  },
  {
    id: 502,
    sport_id: 1,
    name: 'Tajikistan',
    slug: 'tajikistan',
    slug_en: 'tajikistan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 370,
    sportradar_id: 825,
    igubet_name: 'Tajikistan',
    igubet_country_code: 'TJK',
  },
  {
    id: 511,
    sport_id: 1,
    name: 'Tanzania',
    slug: 'tanzania',
    slug_en: 'tanzania',
    match_count_prematch_all: 88,
    match_count_prematch: 88,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 270,
    sportradar_id: 803,
    igubet_name: 'Tanzania',
    igubet_country_code: 'TZA',
  },
  {
    id: 388,
    sport_id: 1,
    name: 'Thailand',
    slug: 'thailand',
    slug_en: 'thailand',
    match_count_prematch_all: 228,
    match_count_prematch: 228,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 644,
    sportradar_id: 485,
    igubet_name: 'Thailand',
    igubet_country_code: 'THA',
  },
  {
    id: 609,
    sport_id: 1,
    name: 'Togo',
    slug: 'togo',
    slug_en: 'togo',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 201,
    sportradar_id: 866,
    igubet_name: 'Togo',
    igubet_country_code: 'TGO',
  },
  {
    id: 530,
    sport_id: 1,
    name: 'Trinidad & Tobago',
    slug: 'trinidad-tobago',
    slug_en: 'trinidad-tobago',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 151,
    sportradar_id: 527,
    igubet_name: 'Trinidad and Tobago',
    igubet_country_code: 'TTO',
  },
  {
    id: 505,
    sport_id: 1,
    name: 'Tunisia',
    slug: 'tunisia',
    slug_en: 'tunisia',
    match_count_prematch_all: 23,
    match_count_prematch: 23,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 70,
    sportradar_id: 378,
    igubet_name: 'Tunisia',
    igubet_country_code: 'TUN',
  },
  {
    id: 405,
    sport_id: 1,
    name: 'Turkey',
    slug: 'turkey',
    slug_en: 'turkey',
    match_count_prematch_all: 1015,
    match_count_prematch: 1015,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 128,
    sportradar_id: 46,
    igubet_name: 'Turkiye',
    igubet_country_code: 'TUR',
  },
  {
    id: 501,
    sport_id: 1,
    name: 'Turkmenistan',
    slug: 'turkmenistan',
    slug_en: 'turkmenistan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 202,
    sportradar_id: 867,
    igubet_name: 'Turkmenistan',
    igubet_country_code: 'TKM',
  },
  {
    id: 524,
    sport_id: 1,
    name: 'Uganda',
    slug: 'uganda',
    slug_en: 'uganda',
    match_count_prematch_all: 104,
    match_count_prematch: 104,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 369,
    sportradar_id: 824,
    igubet_name: 'Uganda',
    igubet_country_code: 'UGA',
  },
  {
    id: 452,
    sport_id: 1,
    name: 'Ukraine',
    slug: 'ukraine',
    slug_en: 'ukraine',
    match_count_prematch_all: 259,
    match_count_prematch: 259,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 598,
    sportradar_id: 86,
    igubet_name: 'Ukraine',
    igubet_country_code: 'UKR',
  },
  {
    id: 461,
    sport_id: 1,
    name: 'United Arab Emirates',
    slug: 'united-arab-emirates',
    slug_en: 'united-arab-emirates',
    match_count_prematch_all: 159,
    match_count_prematch: 159,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 534,
    sportradar_id: 299,
    igubet_name: 'United Arab Emirates',
    igubet_country_code: 'ARE',
  },
  {
    id: 402,
    sport_id: 1,
    name: 'Uruguay',
    slug: 'uruguay',
    slug_en: 'uruguay',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 323,
    sportradar_id: 57,
    igubet_name: 'Uruguay',
    igubet_country_code: 'URY',
  },
  {
    id: 459,
    sport_id: 1,
    name: 'USA',
    slug: 'usa',
    slug_en: 'usa',
    match_count_prematch_all: 477,
    match_count_prematch: 477,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 11,
    sportradar_id: 26,
    igubet_name: 'USA',
    igubet_country_code: 'USA',
  },
  {
    id: 492,
    sport_id: 1,
    name: 'Uzbekistan',
    slug: 'uzbekistan',
    slug_en: 'uzbekistan',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 143,
    sportradar_id: 385,
    igubet_name: 'Uzbekistan',
    igubet_country_code: 'UZB',
  },
  {
    id: 364,
    sport_id: 1,
    name: 'Venezuela',
    slug: 'venezuela',
    slug_en: 'venezuela',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 529,
    sportradar_id: 281,
    igubet_name: 'Venezuela',
    igubet_country_code: 'VEN',
  },
  {
    id: 450,
    sport_id: 1,
    name: 'Vietnam',
    slug: 'vietnam',
    slug_en: 'vietnam',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 108,
    sportradar_id: 366,
    igubet_name: 'Vietnam',
    igubet_country_code: 'VNM',
  },
  {
    id: 444,
    sport_id: 1,
    name: 'Wales',
    slug: 'wales',
    slug_en: 'wales',
    match_count_prematch_all: 158,
    match_count_prematch: 158,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 468,
    sportradar_id: 131,
    igubet_name: 'Wales',
    igubet_country_code: 'WAL',
  },
  {
    id: 453,
    sport_id: 1,
    name: 'Yemen',
    slug: 'yemen',
    slug_en: 'yemen',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 643,
    sportradar_id: 440,
    igubet_name: 'Yemen',
    igubet_country_code: 'YEM',
  },
  {
    id: 512,
    sport_id: 1,
    name: 'Zambia',
    slug: 'zambia',
    slug_en: 'zambia',
    match_count_prematch_all: 128,
    match_count_prematch: 128,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 364,
    sportradar_id: 812,
    igubet_name: 'Zambia',
    igubet_country_code: 'ZMB',
  },
  {
    id: 605,
    sport_id: 1,
    name: 'Zanzibar',
    slug: 'zanzibar',
    slug_en: 'zanzibar',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 418,
    sportradar_id: 955,
    igubet_name: 'Zanzibar',
    igubet_country_code: '',
  },
  {
    id: 523,
    sport_id: 1,
    name: 'Zimbabwe',
    slug: 'zimbabwe',
    slug_en: 'zimbabwe',
    match_count_prematch_all: 0,
    match_count_prematch: 0,
    match_count_inplay: 0,
    order: 0,
    igubet_id: 365,
    sportradar_id: 815,
    igubet_name: 'Zimbabwe',
    igubet_country_code: 'ZWE',
  },
];
